resource "nxos_feature" "example" {
  analytics            = "enabled"
  bash_shell           = "enabled"
  bfd                  = "enabled"
  bgp                  = "enabled"
  dhcp                 = "enabled"
  evpn                 = "enabled"
  grpc                 = "enabled"
  hmm                  = "enabled"
  hsrp                 = "enabled"
  interface_vlan       = "enabled"
  isis                 = "enabled"
  lacp                 = "enabled"
  lldp                 = "enabled"
  macsec               = "enabled"
  netflow              = "enabled"
  ngmvpn               = "enabled"
  ngoam                = "enabled"
  nv_overlay           = "enabled"
  ospf                 = "enabled"
  ospfv3               = "enabled"
  pim                  = "enabled"
  ptp                  = "enabled"
  pvlan                = "enabled"
  sflow                = "enabled"
  scp_server           = "enabled"
  security_group       = "enabled"
  service_acceleration = "enabled"
  sftp_server          = "enabled"
  ssh                  = "enabled"
  tacacs               = "enabled"
  telemetry            = "enabled"
  telnet               = "enabled"
  udld                 = "enabled"
  vn_segment           = "enabled"
  vpc                  = "enabled"
  feature_sets = {
    "fex" = {
      admin_state = "enabled"
    }
  }
}
