---
name: Logging
class_name: loggingLogLevel
dn: sys/logging/loglevel
ds_description: This data source can read the logging configuration.
res_description: This resource can manage the logging configuration.
doc_path: System/logging:LogLevel/
doc_category: System
attributes:
  - nxos_name: all
    tf_name: all
    type: String
    description: "All logging level."
    enum_values:
      - "unspecified"
      - "enableall"
      - "disableall"
    example: "unspecified"
    default_value: "unspecified"
    write_only: true
  - nxos_name: severityLevel
    tf_name: level
    type: String
    description: "Severity level."
    enum_values:
      - "emergencies"
      - "alerts"
      - "critical"
      - "errors"
      - "warnings"
      - "notifications"
      - "information"
      - "debugging"
    example: "information"
    default_value: "notifications"
    write_only: true
child_classes:
  - class_name: loggingFacility
    doc_path: System/logging:Facility/
    rn: facility-[%v]
    tf_name: facilities
    description: List of logging facilities.
    type: list
    mandatory: false
    attributes:
      - nxos_name: facilityName
        tf_name: name
        type: String
        id: true
        description: "Logging facility name."
        enum_values:
          - "spanning-tree"
          - "session-mgr"
          - "radius"
          - "security"
          - "plugin"
          - "cdp"
          - "bootvar"
          - "aaa"
          - "interface-vlan"
          - "vshd"
          - "cfs"
          - "monitor"
          - "ntp"
          - "acllog"
          - "track"
          - "pltfm_config"
          - "lacp"
        example: "spanning-tree"
      - nxos_name: severityLevel
        tf_name: level
        type: String
        description: "Logging severity level."
        enum_values:
          - "emergencies"
          - "alerts"
          - "critical"
          - "errors"
          - "warnings"
          - "notifications"
          - "information"
          - "debugging"
        example: "information"