---
name: NVE VNI Ingress Replication
class_name: nvoIngRepl
dn:  sys/eps/epId-[1]/nws/vni-[%v]/IngRepl
ds_description: This data source can read the configuration of Ingress Replication for Virtual Network ID (VNI).
res_description: This resource can manage the configuration of Ingress Replication for Virtual Network ID (VNI).
doc_path: Network%20Virtualization/nvo:IngRepl/
parents:
  - NVE VNI
attributes:
  - nxos_name: vni
    tf_name: vni
    type: Int64
    id: true
    reference_only: true
    description: 'Virtual Network ID.'
    min_int: 1
    max_int: 16777214
    example: 103100
  - nxos_name: proto
    tf_name: protocol
    type: String
    description: 'Configure VxLAN Ingress Replication mode.'
    enum_values:
      - bgp
      - unknown
      - static
    default_value: unknown
    example: bgp
test_prerequisites:
  - dn: sys/fm/nvo
    class_name: fmNvo
    attributes:
      - name: adminSt
        value: enabled
  - dn: sys/fm/evpn
    class_name: fmEvpn
    attributes:
      - name: adminSt
        value: enabled
    dependencies: [0]
  - dn: sys/eps/epId-[1]
    class_name: nvoEp
    attributes:
      - name: adminSt
        value: enabled
      - name: hostReach
        value: bgp
    dependencies: [1]
  - dn: sys/eps/epId-[1]/nws
    class_name: nvoNws
    dependencies: [2]
  - dn: sys/eps/epId-[1]/nws/vni-[103100]
    class_name: nvoNw
    attributes:
      - name: vni
        value: 103100
    dependencies: [3]