resource "nxos_port_channel_interfaces" "example" {
  items = [{
    interface_id           = "po123"
    port_channel_mode      = "active"
    minimum_links          = 2
    maximum_links          = 10
    suspend_individual     = "disable"
    access_vlan            = "vlan-1"
    admin_state            = "up"
    auto_negotiation       = "on"
    bandwidth              = 0
    delay                  = 1
    description            = "My Description"
    duplex                 = "auto"
    layer                  = "Layer2"
    link_logging           = "enable"
    medium                 = "broadcast"
    mode                   = "access"
    mtu                    = 1500
    native_vlan            = "unknown"
    speed                  = "auto"
    trunk_vlans            = "1-4094"
    dot1q_ether_type       = 33024
    equalization_delay     = 5
    graceful_convergence   = "disable"
    hash_distribution      = "adaptive"
    inherit_bandwidth      = 1000000
    itu_channel            = 50
    lacp_delay_mode        = "enable"
    lacp_vpc_convergence   = "enable"
    link_debounce_down     = 200
    load_defer             = "enable"
    mdix                   = "auto"
    optics_loopback        = "internal"
    port_type              = "leaf"
    pxe_transition_timeout = 5
    router_mac             = "00:00:00:11:22:33"
    snmp_trap_state        = "disable"
    span_mode              = "not-a-span-dest"
    squelch                = "disable"
    transmission_mode      = "not-a-trans-port"
    trunk_logging          = "enable"
    usage                  = "discovery"
    user_configured_flags  = "admin_layer,admin_state"
  }]
}
