resource "nxos_user_management" "example" {
  alphabet_sequence             = 3
  description                   = "User management policy"
  keyboard_sequence             = 3
  max_logins                    = 4
  min_unique                    = 3
  password_grace_time           = 5
  password_life_time            = 90
  password_max_length           = 127
  password_min_length           = 10
  password_secure_mode          = "no"
  password_strength_check       = "no"
  password_warning_time         = 10
  service_password_recovery     = "no"
  pre_login_banner_description  = "Pre-login banner"
  pre_login_banner_name         = "prelogin"
  pre_login_banner_owner_key    = "owner1"
  pre_login_banner_message      = "Authorized users only."
  pre_login_banner_owner_tag    = "tag1"
  post_login_banner_description = "Post-login banner"
  post_login_banner_name        = "postlogin"
  post_login_banner_owner_key   = "owner1"
  post_login_banner_message     = "Welcome to the system."
  post_login_banner_owner_tag   = "tag1"
  users = [{
    name                     = "user1"
    account_status           = "active"
    allow_expired            = "yes"
    clear_password_history   = "no"
    description              = "Test user account"
    email                    = "user1@example.com"
    expiration               = "2030-01-01T00:00:00.000+00:00"
    expires                  = "no"
    first_name               = "John"
    force                    = "no"
    last_name                = "Doe"
    password_hash            = "unspecified"
    phone                    = "1234567890"
    password                 = "password123"
    password_encryption_type = "clear"
    shell_type               = "shellvsh"
    unix_user_id             = 100
    roles = [{
      name           = "network-operator"
      description    = "Operator role"
      privilege_type = "readPriv"
    }]
  }]
  tacacs_deadtime         = 5
  tacacs_description      = "TACACS+ settings"
  tacacs_key              = "secret123"
  tacacs_key_encryption   = "0"
  tacacs_logging_level    = 4
  tacacs_name             = "tacacsplus"
  tacacs_owner_key        = "owner1"
  tacacs_owner_tag        = "tag1"
  tacacs_retries          = 3
  tacacs_source_interface = "unspecified"
  tacacs_timeout          = 10
  tacacs_providers = [{
    name                     = "10.1.1.1"
    authentication_protocol  = "chap"
    description              = "TACACS+ provider"
    key                      = "secret123"
    key_encryption           = "0"
    monitoring_idle_time     = 10
    monitoring_password      = "monpass"
    monitoring_password_type = "0"
    monitoring_user          = "monuser"
    owner_key                = "owner1"
    owner_tag                = "tag1"
    port                     = 149
    retries                  = 3
    single_connection        = "yes"
    timeout                  = 10
  }]
  tacacs_provider_groups = [{
    name             = "TACACS_GROUP1"
    deadtime         = 5
    description      = "TACACS+ provider group"
    owner_key        = "owner1"
    owner_tag        = "tag1"
    source_interface = "unspecified"
    vrf              = "default"
  }]
}
