resource "nxos_snmp" "example" {
  admin_state = "enabled"
  instance_admin_state = "enabled"
  description = "My SNMP instance"
  engine_id = "00:00:00:63:00:01:00:10:20:15:10:03"
  logging_level = "warnings"
  owner_key = "key1"
  owner_tag = "tag1"
  unknown_engine_id = "no"
  unknown_user = "no"
  contact = "admin@example.com"
  system_info_description = "My NX-OS device"
  location = "DC1-Room42"
  packet_size = 8192
  disable_aaa_sync = "yes"
  enforce_privacy = "yes"
  tcp_session_authentication = "tcpSessAuth"
  source_interface_traps = "eth1/1"
  local_users = {
    "user1" = {
      authentication_password = "Xe9$mK2v!pQr"
      authentication_type = "md5"
      ipv4_acl_name = "snmp-acl-v4"
      ipv6_acl_name = "snmp-acl-v6"
      enforce_privacy = false
      localized_v2_key = false
      localized_key = false
      privacy_password = "Yt4&nL8w!kDs"
      privacy_type = "des"
      password_type = 0
      engine_id = "00:00:00:63:00:01:00:10:20:15:10:03"
      engine_id_length = 0
      groups = {
        "network-operator" = {}
      }
    }
  }
  hosts = {
    "10.0.0.1;1162" = {
      community_name = "public"
      notification_type = "traps"
      security_level = "auth"
      version = "v3"
      vrfs = {
        "management" = {}
      }
    }
  }
  enable_all = "yes"
  aaa_server_state_change_trap_status = "enable"
  bfd_session_down_trap_status = "enable"
  bfd_session_up_trap_status = "enable"
  bridge_new_root_trap_status = "enable"
  bridge_topology_change_trap_status = "enable"
  callhome_event_notify_trap_status = "enable"
  callhome_smtp_send_fail_trap_status = "enable"
  cfs_state_change_notif_trap_status = "enable"
  cfs_merge_failure_trap_status = "enable"
  config_cli_running_config_change_trap_status = "enable"
  entity_mib_change_trap_status = "enable"
  entity_mib_enable_status_notification_trap_status = "enable"
  entity_fan_status_change_trap_status = "enable"
  entity_module_inserted_trap_status = "enable"
  entity_module_removed_trap_status = "enable"
  entity_module_status_change_trap_status = "enable"
  entity_power_out_change_trap_status = "enable"
  entity_power_status_change_trap_status = "enable"
  entity_sensor_trap_status = "enable"
  entity_unrecognised_module_trap_status = "enable"
  fcdomain_domain_id_not_assigned_trap_status = "enable"
  fcdomain_fabric_change_trap_status = "enable"
  fcdomain_new_principal_switch_trap_status = "enable"
  feature_control_op_status_change_trap_status = "enable"
  feature_control_cisco_op_status_change_trap_status = "enable"
  generic_cold_start_trap_status = "enable"
  generic_warm_start_trap_status = "enable"
  hsrp_state_change_trap_status = "enable"
  license_expiry_trap_status = "enable"
  license_expiry_warning_trap_status = "enable"
  license_file_missing_trap_status = "enable"
  license_no_license_for_feature_trap_status = "enable"
  link_cie_link_down_trap_status = "enable"
  link_cie_link_up_trap_status = "enable"
  link_cisco_xcvr_mon_status_change_trap_status = "enable"
  link_cmn_mac_move_notification_trap_status = "enable"
  link_delayed_link_state_change_trap_status = "enable"
  link_extended_link_down_trap_status = "enable"
  link_extended_link_up_trap_status = "enable"
  link_link_down_trap_status = "enable"
  link_link_up_trap_status = "enable"
  link_err_disable_interface_event_trap_status = "enable"
  lldp_rem_tables_change_trap_status = "enable"
  mmode_maint_mode_change_trap_status = "enable"
  mmode_normal_mode_change_trap_status = "enable"
  mpls_ldp_trap_status = "enable"
  mpls_ldp_session_down_trap_status = "enable"
  mpls_ldp_session_up_trap_status = "enable"
  mpls_vpn_trap_status = "enable"
  mpls_vpn_max_thresh_cleared_trap_status = "enable"
  mpls_vpn_max_thresh_exceeded_trap_status = "enable"
  mpls_vpn_mid_thresh_exceeded_trap_status = "enable"
  mpls_vpn_vrf_down_trap_status = "enable"
  mpls_vpn_vrf_up_trap_status = "enable"
  msdp_backward_transition_trap_status = "enable"
  pim_neighbor_loss_trap_status = "enable"
  port_security_access_secure_mac_violation_trap_status = "enable"
  port_security_trunk_secure_mac_violation_trap_status = "enable"
  rf_redundancy_framework_trap_status = "enable"
  rmon_rising_alarm_trap_status = "enable"
  rmon_falling_alarm_trap_status = "enable"
  rmon_hc_rising_alarm_trap_status = "enable"
  rmon_hc_falling_alarm_trap_status = "enable"
  snmp_authentication_trap_status = "enable"
  storm_control_cpsc_event_trap_status = "enable"
  stpx_inconsistency_trap_status = "enable"
  stpx_loop_inconsistency_trap_status = "enable"
  stpx_root_inconsistency_trap_status = "enable"
  syslog_message_generated_trap_status = "enable"
  sysmgr_fail_sw_core_notify_trap_status = "enable"
  system_clock_change_notification_trap_status = "enable"
  upgrade_job_status_notify_trap_status = "enable"
  upgrade_op_notify_on_completion_trap_status = "enable"
  vtp_notifs_trap_status = "enable"
  vtp_vlan_create_trap_status = "enable"
  vtp_vlan_delete_trap_status = "enable"
  rmon_events = {
    "1" = {
      description = "Test event"
      log = "yes"
      owner = "admin"
      trap = "public"
    }
  }
}
