// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-nxos/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-nxos"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &IPv4DataSource{}
	_ datasource.DataSourceWithConfigure = &IPv4DataSource{}
)

func NewIPv4DataSource() datasource.DataSource {
	return &IPv4DataSource{}
}

type IPv4DataSource struct {
	data *NxosProviderData
}

func (d *IPv4DataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ipv4"
}

func (d *IPv4DataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: helpers.NewResourceDescription("This data source can read the IPv4 configuration on NX-OS devices, including per-VRF static routes with next hops and interface addresses.", "ipv4Entity", "Layer%203/ipv4:Entity/").AddAdditionalDocs([]string{"ipv4Inst", "ipv4Dom", "ipv4Route", "ipv4Nexthop", "ipv4If", "ipv4Addr"}, []string{"Layer%203/ipv4:Inst/", "Layer%203/ipv4:Dom/", "Layer%203/ipv4:Route/", "Layer%203/ipv4:Nexthop/", "Layer%203/ipv4:If/", "Layer%203/ipv4:Addr/"}).String,

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The distinguished name of the object.",
				Computed:            true,
			},
			"vrfs": schema.ListNestedAttribute{
				MarkdownDescription: "List of IPv4 VRF configurations.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the object.",
							Computed:            true,
						},
						"static_routes": schema.ListNestedAttribute{
							MarkdownDescription: "List of IPv4 static routes.",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"prefix": schema.StringAttribute{
										MarkdownDescription: "Prefix.",
										Computed:            true,
									},
									"next_hops": schema.ListNestedAttribute{
										MarkdownDescription: "List of next hops.",
										Computed:            true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"interface_id": schema.StringAttribute{
													MarkdownDescription: "Nexthop Interface. Must match first field in the output of `show intf brief` or `unspecified`. Example: `eth1/1` or `vlan100`.",
													Computed:            true,
												},
												"address": schema.StringAttribute{
													MarkdownDescription: "Nexthop Address.",
													Computed:            true,
												},
												"vrf_name": schema.StringAttribute{
													MarkdownDescription: "Nexthop VRF.",
													Computed:            true,
												},
												"description": schema.StringAttribute{
													MarkdownDescription: "Description of the specified attribute.",
													Computed:            true,
												},
												"object": schema.Int64Attribute{
													MarkdownDescription: "Object to be tracked.",
													Computed:            true,
												},
												"preference": schema.Int64Attribute{
													MarkdownDescription: "Route preference.",
													Computed:            true,
												},
												"tag": schema.Int64Attribute{
													MarkdownDescription: "Tag value.",
													Computed:            true,
												},
											},
										},
									},
								},
							},
						},
						"interfaces": schema.ListNestedAttribute{
							MarkdownDescription: "List of IPv4 interfaces.",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"interface_id": schema.StringAttribute{
										MarkdownDescription: "Must match first field in the output of `show intf brief`. Example: `eth1/1`.",
										Computed:            true,
									},
									"drop_glean": schema.StringAttribute{
										MarkdownDescription: "ip drop-glean enabled/disabled.",
										Computed:            true,
									},
									"forward": schema.StringAttribute{
										MarkdownDescription: "IP forward.",
										Computed:            true,
									},
									"unnumbered": schema.StringAttribute{
										MarkdownDescription: "IP unnumbered. Reference to interface must match first field in the output of `show intf brief`. Example: `eth1/1`.",
										Computed:            true,
									},
									"urpf": schema.StringAttribute{
										MarkdownDescription: "URPF Info.",
										Computed:            true,
									},
									"addresses": schema.ListNestedAttribute{
										MarkdownDescription: "List of IPv4 interface addresses.",
										Computed:            true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"address": schema.StringAttribute{
													MarkdownDescription: "Address.",
													Computed:            true,
												},
												"type": schema.StringAttribute{
													MarkdownDescription: "Type.",
													Computed:            true,
												},
												"tag": schema.Int64Attribute{
													MarkdownDescription: "Route Tag.",
													Computed:            true,
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (d *IPv4DataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.data = req.ProviderData.(*NxosProviderData)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin read
func (d *IPv4DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config IPv4

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getDn()))

	device, ok := d.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to find device '%s' in provider configuration", config.Device.ValueString()))
		return
	}

	queries := []func(*nxos.Req){}
	queries = append(queries, nxos.Query("rsp-subtree-depth", "4"))
	res, err := device.Client.GetDn(config.getDn(), queries...)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
		return
	}

	config.fromBody(res)
	config.Dn = types.StringValue(config.getDn())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getDn()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read
