// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosRoutePolicy(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "ipv4_prefix_lists.*", map[string]string{
		"name": "PREFIX_LIST1",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "ipv4_prefix_lists.*.entries.*", map[string]string{
		"order":      "10",
		"action":     "permit",
		"criteria":   "inexact",
		"prefix":     "192.168.1.0/24",
		"from_range": "26",
		"to_range":   "32",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "route_maps.*", map[string]string{
		"name": "ROUTE_MAP1",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "route_maps.*.entries.*", map[string]string{
		"order":  "10",
		"action": "permit",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "route_maps.*.entries.*.match_route_prefix_lists.*", map[string]string{
		"prefix_list_dn": "sys/rpm/pfxlistv4-[PREFIX_LIST1]",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "route_maps.*.entries.*", map[string]string{
		"additive":     "disabled",
		"no_community": "disabled",
		"set_criteria": "none",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "route_maps.*.entries.*.set_regular_community_items.*", map[string]string{
		"community": "regular:as2-nn2:65001:123",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_route_policy.test", "route_maps.*.entries.*.match_tags.*", map[string]string{
		"tag": "12345",
	}))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosRoutePolicyConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosRoutePolicyConfig() string {
	config := `resource "nxos_route_policy" "test" {` + "\n"
	config += `	ipv4_prefix_lists = [{` + "\n"
	config += `		name = "PREFIX_LIST1"` + "\n"
	config += `		entries = [{` + "\n"
	config += `			order = 10` + "\n"
	config += `			action = "permit"` + "\n"
	config += `			criteria = "inexact"` + "\n"
	config += `			prefix = "192.168.1.0/24"` + "\n"
	config += `			from_range = 26` + "\n"
	config += `			to_range = 32` + "\n"
	config += `		}]` + "\n"
	config += `	}]` + "\n"
	config += `	route_maps = [{` + "\n"
	config += `		name = "ROUTE_MAP1"` + "\n"
	config += `		entries = [{` + "\n"
	config += `			order = 10` + "\n"
	config += `			action = "permit"` + "\n"
	config += `			match_route_prefix_lists = [{` + "\n"
	config += `				prefix_list_dn = "sys/rpm/pfxlistv4-[PREFIX_LIST1]"` + "\n"
	config += `			}]` + "\n"
	config += `			additive = "disabled"` + "\n"
	config += `			no_community = "disabled"` + "\n"
	config += `			set_criteria = "none"` + "\n"
	config += `			set_regular_community_items = [{` + "\n"
	config += `				community = "regular:as2-nn2:65001:123"` + "\n"
	config += `			}]` + "\n"
	config += `			match_tags = [{` + "\n"
	config += `				tag = 12345` + "\n"
	config += `			}]` + "\n"
	config += `		}]` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_route_policy" "test" {
	depends_on = [nxos_route_policy.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
