// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosPIM(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "instance_admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "control", "stateful-ha"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "evpn_border_leaf", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "extra_net", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "join_prune_delay", "200"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "register_stop", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.bfd", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.auto_enable", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.control", "flush-on-restart"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.flush_routes", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.join_prune_delay", "200"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.log_neighbor_changes", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.mtu", "1600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.register_rate_limit", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.rfc_strict", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.spt_switch_graceful", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.bfd", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.dr_priority", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.passive", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.sparse_mode", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.border", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.border_router", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.control", "border"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.description", "MyDescription"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.dr_delay", "5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.join_prune_route_map", "JP_POLICY"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.name", "pim-if"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.neighbor_route_map", "NEIGH_POLICY"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.pfm_sd_boundary", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.interfaces.eth1/10.rfc_strict", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.ssm_policy_name", "SSM"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.ssm_policy_description", "SSM_Policy"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.ssm_range_group_list_1", "232.0.0.0/8"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.ssm_range_group_list_2", "233.0.0.0/8"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.ssm_range_none", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.static_rp_policy_name", "RP"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.static_rp_policy_description", "Static_RP_Policy"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.static_rps.1.2.3.4.group_lists.224.0.0.0/4.bidir", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.static_rps.1.2.3.4.group_lists.224.0.0.0/4.override", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.anycast_rp_local_interface", "eth1/10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.anycast_rp_source_interface", "eth1/10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.anycast_rp_description", "Anycast_RP"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim.test", "vrfs.default.anycast_rp_name", "anycast-rp"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosPIMPrerequisitesConfig + testAccDataSourceNxosPIMConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceNxosPIMPrerequisitesConfig = `
resource "nxos_dme" "PreReq0" {
  dn = "sys/intf/phys-[eth1/10]"
  class_name = "l1PhysIf"
  content = {
      id = "eth1/10"
      layer = "Layer3"
  }
}

resource "nxos_dme" "PreReq1" {
  dn = "sys/fm/pim"
  class_name = "fmPim"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosPIMConfig() string {
	config := `resource "nxos_pim" "test" {` + "\n"
	config += `	admin_state = "enabled"` + "\n"
	config += `	instance_admin_state = "enabled"` + "\n"
	config += `	control = "stateful-ha"` + "\n"
	config += `	evpn_border_leaf = false` + "\n"
	config += `	extra_net = false` + "\n"
	config += `	join_prune_delay = 200` + "\n"
	config += `	register_stop = false` + "\n"
	config += `	vrfs = {` + "\n"
	config += `		"default" = {` + "\n"
	config += `			admin_state = "enabled"` + "\n"
	config += `			bfd = true` + "\n"
	config += `			auto_enable = false` + "\n"
	config += `			control = "flush-on-restart"` + "\n"
	config += `			flush_routes = false` + "\n"
	config += `			join_prune_delay = 200` + "\n"
	config += `			log_neighbor_changes = false` + "\n"
	config += `			mtu = 1600` + "\n"
	config += `			register_rate_limit = 100` + "\n"
	config += `			rfc_strict = false` + "\n"
	config += `			spt_switch_graceful = false` + "\n"
	config += `			interfaces = {` + "\n"
	config += `				"eth1/10" = {` + "\n"
	config += `					admin_state = "enabled"` + "\n"
	config += `					bfd = "enabled"` + "\n"
	config += `					dr_priority = 10` + "\n"
	config += `					passive = false` + "\n"
	config += `					sparse_mode = true` + "\n"
	config += `					border = false` + "\n"
	config += `					border_router = false` + "\n"
	config += `					control = "border"` + "\n"
	config += `					description = "MyDescription"` + "\n"
	config += `					dr_delay = 5` + "\n"
	config += `					join_prune_route_map = "JP_POLICY"` + "\n"
	config += `					name = "pim-if"` + "\n"
	config += `					neighbor_route_map = "NEIGH_POLICY"` + "\n"
	config += `					pfm_sd_boundary = 0` + "\n"
	config += `					rfc_strict = false` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `			ssm_policy_name = "SSM"` + "\n"
	config += `			ssm_policy_description = "SSM_Policy"` + "\n"
	config += `			ssm_range_group_list_1 = "232.0.0.0/8"` + "\n"
	config += `			ssm_range_group_list_2 = "233.0.0.0/8"` + "\n"
	config += `			ssm_range_none = false` + "\n"
	config += `			static_rp_policy_name = "RP"` + "\n"
	config += `			static_rp_policy_description = "Static_RP_Policy"` + "\n"
	config += `			static_rps = {` + "\n"
	config += `				"1.2.3.4" = {` + "\n"
	config += `					group_lists = {` + "\n"
	config += `						"224.0.0.0/4" = {` + "\n"
	config += `							bidir = true` + "\n"
	config += `							override = true` + "\n"
	config += `						}` + "\n"
	config += `					}` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `			anycast_rp_local_interface = "eth1/10"` + "\n"
	config += `			anycast_rp_source_interface = "eth1/10"` + "\n"
	config += `			anycast_rp_description = "Anycast_RP"` + "\n"
	config += `			anycast_rp_name = "anycast-rp"` + "\n"
	config += `			anycast_rp_peers = {` + "\n"
	config += `				"10.1.1.1/32|20.1.1.1/32" = {` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	depends_on = [nxos_dme.PreReq0, nxos_dme.PreReq1, ]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_pim" "test" {
	depends_on = [nxos_pim.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
