// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosOSPF(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.control", "stateful-ha"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.log_adjacency_changes", "brief"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.bandwidth_reference", "400000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.bandwidth_reference_unit", "mbps"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.distance", "110"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.router_id", "34.56.78.90"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.capability_vrf_lite", "l3vpn"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.control", "bfd,default-passive"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.default_metric", "1000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.default_route_nssa_pbit_clear", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.discard_route", "ext,int"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.down_bit_ignore", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.max_ecmp", "16"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.name_lookup_vrf", "default"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.rfc1583_compatible", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.rfc1583_compatible_ios", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.areas.0.0.0.10.authentication_type", "unspecified"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.areas.0.0.0.10.cost", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.areas.0.0.0.10.control", "summary"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.areas.0.0.0.10.nssa_translator_role", "always"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.areas.0.0.0.10.segment_routing_mpls", "mpls"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.areas.0.0.0.10.type", "stub"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.max_metric_await_convergence_bgp_asn", "65535"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.max_metric_control", "external-lsa,startup,stub,summary-lsa"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.max_metric_external_lsa", "600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.max_metric_summary_lsa", "600"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.max_metric_startup_interval", "300"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.advertise_secondaries", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.area", "0.0.0.10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.bfd", "disabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.cost", "1000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.dead_interval", "60"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.hello_interval", "15"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.network_type", "p2p"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.passive", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.priority", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.control", "mtu-ignore"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.node_flag", "clear"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.retransmit_interval", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.transmit_delay", "2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.authentication_key_id", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.authentication_key_secure_mode", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.authentication_keychain", "mykeychain"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.authentication_md5_key_secure_mode", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.interfaces.eth1/10.authentication_type", "none"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.redistributions.static;none;none.always", "no"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.redistributions.static;none;none.route_map", "route_map_ospf"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ospf.test", "instances.OSPF1.vrfs.VRF1.redistributions.static;none;none.srv6_prefix_type", "unspecified"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosOSPFPrerequisitesConfig + testAccDataSourceNxosOSPFConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceNxosOSPFPrerequisitesConfig = `
resource "nxos_dme" "PreReq0" {
  dn = "sys/fm/ospf"
  class_name = "fmOspf"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

resource "nxos_dme" "PreReq1" {
  dn = "sys/fm/bfd"
  class_name = "fmBfd"
  delete = false
  content = {
      adminSt = "enabled"
  }
  depends_on = [nxos_dme.PreReq0, ]
}

resource "nxos_dme" "PreReq2" {
  dn = "sys/intf/phys-[eth1/10]"
  class_name = "l1PhysIf"
  content = {
      layer = "Layer3"
  }
  depends_on = [nxos_dme.PreReq1, ]
}

resource "nxos_dme" "PreReq3" {
  dn = "sys/intf/phys-[eth1/10]/rtvrfMbr"
  class_name = "nwRtVrfMbr"
  content = {
      tDn = "sys/inst-VRF1"
  }
  depends_on = [nxos_dme.PreReq2, ]
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosOSPFConfig() string {
	config := `resource "nxos_ospf" "test" {` + "\n"
	config += `	admin_state = "enabled"` + "\n"
	config += `	instances = {` + "\n"
	config += `		"OSPF1" = {` + "\n"
	config += `			admin_state = "enabled"` + "\n"
	config += `			control = "stateful-ha"` + "\n"
	config += `			vrfs = {` + "\n"
	config += `				"VRF1" = {` + "\n"
	config += `					log_adjacency_changes = "brief"` + "\n"
	config += `					admin_state = "enabled"` + "\n"
	config += `					bandwidth_reference = 400000` + "\n"
	config += `					bandwidth_reference_unit = "mbps"` + "\n"
	config += `					distance = 110` + "\n"
	config += `					router_id = "34.56.78.90"` + "\n"
	config += `					capability_vrf_lite = "l3vpn"` + "\n"
	config += `					control = "bfd,default-passive"` + "\n"
	config += `					default_metric = 1000` + "\n"
	config += `					default_route_nssa_pbit_clear = true` + "\n"
	config += `					discard_route = "ext,int"` + "\n"
	config += `					down_bit_ignore = true` + "\n"
	config += `					max_ecmp = 16` + "\n"
	config += `					name_lookup_vrf = "default"` + "\n"
	config += `					rfc1583_compatible = true` + "\n"
	config += `					rfc1583_compatible_ios = true` + "\n"
	config += `					areas = {` + "\n"
	config += `						"0.0.0.10" = {` + "\n"
	config += `							authentication_type = "unspecified"` + "\n"
	config += `							cost = 10` + "\n"
	config += `							control = "summary"` + "\n"
	config += `							nssa_translator_role = "always"` + "\n"
	config += `							segment_routing_mpls = "mpls"` + "\n"
	config += `							type = "stub"` + "\n"
	config += `						}` + "\n"
	config += `					}` + "\n"
	config += `					max_metric_await_convergence_bgp_asn = "65535"` + "\n"
	config += `					max_metric_control = "external-lsa,startup,stub,summary-lsa"` + "\n"
	config += `					max_metric_external_lsa = 600` + "\n"
	config += `					max_metric_summary_lsa = 600` + "\n"
	config += `					max_metric_startup_interval = 300` + "\n"
	config += `					interfaces = {` + "\n"
	config += `						"eth1/10" = {` + "\n"
	config += `							admin_state = "enabled"` + "\n"
	config += `							advertise_secondaries = false` + "\n"
	config += `							area = "0.0.0.10"` + "\n"
	config += `							bfd = "disabled"` + "\n"
	config += `							cost = 1000` + "\n"
	config += `							dead_interval = 60` + "\n"
	config += `							hello_interval = 15` + "\n"
	config += `							network_type = "p2p"` + "\n"
	config += `							passive = "enabled"` + "\n"
	config += `							priority = 10` + "\n"
	config += `							control = "mtu-ignore"` + "\n"
	config += `							node_flag = "clear"` + "\n"
	config += `							retransmit_interval = 10` + "\n"
	config += `							transmit_delay = 2` + "\n"
	config += `							authentication_key = "0 mykey"` + "\n"
	config += `							authentication_key_id = 1` + "\n"
	config += `							authentication_key_new = "0 mykey"` + "\n"
	config += `							authentication_key_secure_mode = false` + "\n"
	config += `							authentication_keychain = "mykeychain"` + "\n"
	config += `							authentication_md5_key = "0 mymd5key"` + "\n"
	config += `							authentication_md5_key_new = "0 mymd5key"` + "\n"
	config += `							authentication_md5_key_secure_mode = false` + "\n"
	config += `							authentication_type = "none"` + "\n"
	config += `						}` + "\n"
	config += `					}` + "\n"
	config += `					redistributions = {` + "\n"
	config += `						"static;none;none" = {` + "\n"
	config += `							always = "no"` + "\n"
	config += `							route_map = "route_map_ospf"` + "\n"
	config += `							srv6_prefix_type = "unspecified"` + "\n"
	config += `						}` + "\n"
	config += `					}` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	depends_on = [nxos_dme.PreReq0, nxos_dme.PreReq1, nxos_dme.PreReq2, nxos_dme.PreReq3, ]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_ospf" "test" {
	depends_on = [nxos_ospf.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
