// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosVPC(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "instance_admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "control", "stateful-ha"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "domain_admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "domain_id", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "auto_recovery", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "auto_recovery_interval", "480"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "delay_restore_orphan_port", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "delay_restore_svi", "20"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "delay_restore_vpc", "60"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "dscp", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "fast_convergence", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "graceful_consistency_check", "disabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "l3_peer_router", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "l3_peer_router_syslog", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "l3_peer_router_syslog_interval", "3000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peer_gateway", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peer_ip", "1.2.3.4"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peer_switch", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "role_priority", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "sys_mac", "01:01:01:01:01:01"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "system_priority", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "track", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "virtual_ip", "1.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "delay_peer_link_bringup", "60"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "exclude_svi", "1-2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "mac_bpdu_source_version_2", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peer_gateway_exclude_vlan", "1-2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_destination_ip", "192.168.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_flush_timeout", "3"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_interval", "1000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_precedence_type", "network"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_precedence_value", "6"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_source_ip", "192.168.1.2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_timeout", "5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_type_of_service_byte", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_type_of_service_configuration_type", "noCfg"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_type_of_service_type", "min-delay"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_type_of_service_value", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_udp_port", "1234"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "keepalive_vrf", "management"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peerlink_port_channel_id", "eth1/9"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peerlink_admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_vpc.test", "peerlink_description", "My description"))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_vpc.test", "interfaces.*", map[string]string{
		"vpc_interface_id": "1",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_vpc.test", "interfaces.*", map[string]string{
		"port_channel_interface_dn": "sys/intf/aggr-[po1]",
	}))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosVPCPrerequisitesConfig + testAccDataSourceNxosVPCConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceNxosVPCPrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/fm/vpc"
  class_name = "fmVpc"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

resource "nxos_rest" "PreReq1" {
  dn = "sys/fm/lacp"
  class_name = "fmLacp"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

resource "nxos_rest" "PreReq2" {
  dn = "sys/intf/aggr-[po1]"
  class_name = "pcAggrIf"
  content = {
      id = "po1"
  }
  depends_on = [nxos_rest.PreReq1, ]
}

resource "nxos_rest" "PreReq3" {
  dn = "sys/intf/phys-[eth1/9]"
  class_name = "l1PhysIf"
  content = {
      layer = "Layer2"
  }
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosVPCConfig() string {
	config := `resource "nxos_vpc" "test" {` + "\n"
	config += `	admin_state = "enabled"` + "\n"
	config += `	instance_admin_state = "enabled"` + "\n"
	config += `	control = "stateful-ha"` + "\n"
	config += `	domain_admin_state = "enabled"` + "\n"
	config += `	domain_id = 100` + "\n"
	config += `	auto_recovery = "enabled"` + "\n"
	config += `	auto_recovery_interval = 480` + "\n"
	config += `	delay_restore_orphan_port = 10` + "\n"
	config += `	delay_restore_svi = 20` + "\n"
	config += `	delay_restore_vpc = 60` + "\n"
	config += `	dscp = 0` + "\n"
	config += `	fast_convergence = "enabled"` + "\n"
	config += `	graceful_consistency_check = "disabled"` + "\n"
	config += `	l3_peer_router = "enabled"` + "\n"
	config += `	l3_peer_router_syslog = "enabled"` + "\n"
	config += `	l3_peer_router_syslog_interval = 3000` + "\n"
	config += `	peer_gateway = "enabled"` + "\n"
	config += `	peer_ip = "1.2.3.4"` + "\n"
	config += `	peer_switch = "enabled"` + "\n"
	config += `	role_priority = 100` + "\n"
	config += `	sys_mac = "01:01:01:01:01:01"` + "\n"
	config += `	system_priority = 100` + "\n"
	config += `	track = 10` + "\n"
	config += `	virtual_ip = "1.1.1.1"` + "\n"
	config += `	delay_peer_link_bringup = 60` + "\n"
	config += `	exclude_svi = "1-2"` + "\n"
	config += `	mac_bpdu_source_version_2 = false` + "\n"
	config += `	peer_gateway_exclude_vlan = "1-2"` + "\n"
	config += `	keepalive_destination_ip = "192.168.1.1"` + "\n"
	config += `	keepalive_flush_timeout = 3` + "\n"
	config += `	keepalive_interval = 1000` + "\n"
	config += `	keepalive_precedence_type = "network"` + "\n"
	config += `	keepalive_precedence_value = 6` + "\n"
	config += `	keepalive_source_ip = "192.168.1.2"` + "\n"
	config += `	keepalive_timeout = 5` + "\n"
	config += `	keepalive_type_of_service_byte = 0` + "\n"
	config += `	keepalive_type_of_service_configuration_type = "noCfg"` + "\n"
	config += `	keepalive_type_of_service_type = "min-delay"` + "\n"
	config += `	keepalive_type_of_service_value = 0` + "\n"
	config += `	keepalive_udp_port = 1234` + "\n"
	config += `	keepalive_vrf = "management"` + "\n"
	config += `	peerlink_port_channel_id = "eth1/9"` + "\n"
	config += `	peerlink_admin_state = "enabled"` + "\n"
	config += `	peerlink_description = "My description"` + "\n"
	config += `	interfaces = [{` + "\n"
	config += `		vpc_interface_id = 1` + "\n"
	config += `		port_channel_interface_dn = "sys/intf/aggr-[po1]"` + "\n"
	config += `	}]` + "\n"
	config += `	depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, nxos_rest.PreReq3, ]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_vpc" "test" {
	depends_on = [nxos_vpc.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
