// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceNxosBGPPeer(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosBGPPeerPrerequisitesConfig + testAccDataSourceNxosBGPPeerConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "address", "192.168.0.1"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "remote_asn", "65002"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "description", "My description"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "peer_template", "SPINE-PEERS"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "peer_type", "fabric-internal"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "source_interface", "lo0"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "hold_time", "5"),
					resource.TestCheckResourceAttr("data.nxos_bgp_peer.test", "keepalive", "15"),
				),
			},
		},
	})
}

const testAccDataSourceNxosBGPPeerPrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/fm/bgp"
  class_name = "fmBgp"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

resource "nxos_rest" "PreReq1" {
  dn = "sys/bgp"
  class_name = "bgpEntity"
  content = {
  }
  depends_on = [nxos_rest.PreReq0, ]
}

resource "nxos_rest" "PreReq2" {
  dn = "sys/bgp/inst"
  class_name = "bgpInst"
  content = {
      adminSt = "enabled"
      asn = "65001"
  }
  depends_on = [nxos_rest.PreReq1, ]
}

resource "nxos_rest" "PreReq3" {
  dn = "sys/bgp/inst/dom-[default]"
  class_name = "bgpDom"
  content = {
      name = "default"
  }
  depends_on = [nxos_rest.PreReq2, ]
}

`

const testAccDataSourceNxosBGPPeerConfig = `

resource "nxos_bgp_peer" "test" {
  asn = "65001"
  vrf = "default"
  address = "192.168.0.1"
  remote_asn = "65002"
  description = "My description"
  peer_template = "SPINE-PEERS"
  peer_type = "fabric-internal"
  source_interface = "lo0"
  hold_time = 5
  keepalive = 15
  depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, nxos_rest.PreReq3, ]
}

data "nxos_bgp_peer" "test" {
  asn = "65001"
  vrf = "default"
  address = "192.168.0.1"
  depends_on = [nxos_bgp_peer.test]
}
`
