// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceNxosBGPInstanceDomainPeerContainer(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosBGPInstanceDomainPeerContainerPrerequisitesConfig + testAccDataSourceNxosBGPInstanceDomainPeerContainerConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.nxos_bgp_instance_domain_peercontainer.test", "template_name", "SPINE-PEERS"),
					resource.TestCheckResourceAttr("data.nxos_bgp_instance_domain_peercontainer.test", "asn", "65002"),
					resource.TestCheckResourceAttr("data.nxos_bgp_instance_domain_peercontainer.test", "peer_type", "fabric-internal"),
					resource.TestCheckResourceAttr("data.nxos_bgp_instance_domain_peercontainer.test", "source_interface", "lo0"),
				),
			},
		},
	})
}

const testAccDataSourceNxosBGPInstanceDomainPeerContainerPrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/bgp"
  class_name = "bgpEntity"
  content = {
  }
}

resource "nxos_rest" "PreReq1" {
  dn = "sys/bgp/inst"
  class_name = "bgpInst"
  content = {
      adminSt = "enabled"
      asn = "65001"
  }
  depends_on = [nxos_rest.PreReq0, ]
}

resource "nxos_rest" "PreReq2" {
  dn = "sys/bgp/inst/dom-[default]"
  class_name = "bgpDom"
  content = {
      name = "default"
  }
  depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, ]
}

`

const testAccDataSourceNxosBGPInstanceDomainPeerContainerConfig = `

resource "nxos_bgp_instance_domain_peercontainer" "test" {
  vrf = "default"
  template_name = "SPINE-PEERS"
  asn = "65002"
  peer_type = "fabric-internal"
  source_interface = "lo0"
  depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, ]
}

data "nxos_bgp_instance_domain_peercontainer" "test" {
  vrf = "default"
  template_name = "SPINE-PEERS"
  depends_on = [nxos_bgp_instance_domain_peercontainer.test]
}
`
