// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosSVIInterfaces(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_svi_interfaces.test", "svi_interfaces.*", map[string]string{
		"interface_id":            "vlan293",
		"admin_state":             "down",
		"autostate":               "false",
		"bandwidth":               "1000",
		"carrier_delay":           "200",
		"delay":                   "10",
		"description":             "My Description",
		"inband_management":       "false",
		"load_interval_counter_1": "90",
		"load_interval_counter_2": "120",
		"load_interval_counter_3": "90",
		"mac_address":             "00:25:B5:00:00:01",
		"medium":                  "bcast",
		"mtu":                     "9216",
		"mtu_inherit":             "false",
		"snmp_trap_link_status":   "false",
	}))
	checks = append(checks, resource.TestCheckTypeSetElemNestedAttrs("data.nxos_svi_interfaces.test", "svi_interfaces.*", map[string]string{
		"vrf_dn": "sys/inst-VRF123",
	}))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosSVIInterfacesPrerequisitesConfig + testAccDataSourceNxosSVIInterfacesConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceNxosSVIInterfacesPrerequisitesConfig = `
resource "nxos_dme" "PreReq0" {
  dn = "sys/fm/ifvlan"
  class_name = "fmInterfaceVlan"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosSVIInterfacesConfig() string {
	config := `resource "nxos_svi_interfaces" "test" {` + "\n"
	config += `	svi_interfaces = [{` + "\n"
	config += `		interface_id = "vlan293"` + "\n"
	config += `		admin_state = "down"` + "\n"
	config += `		autostate = false` + "\n"
	config += `		bandwidth = 1000` + "\n"
	config += `		carrier_delay = 200` + "\n"
	config += `		delay = 10` + "\n"
	config += `		description = "My Description"` + "\n"
	config += `		inband_management = false` + "\n"
	config += `		load_interval_counter_1 = 90` + "\n"
	config += `		load_interval_counter_2 = 120` + "\n"
	config += `		load_interval_counter_3 = 90` + "\n"
	config += `		mac_address = "00:25:B5:00:00:01"` + "\n"
	config += `		medium = "bcast"` + "\n"
	config += `		mtu = 9216` + "\n"
	config += `		mtu_inherit = false` + "\n"
	config += `		snmp_trap_link_status = false` + "\n"
	config += `		vrf_dn = "sys/inst-VRF123"` + "\n"
	config += `	}]` + "\n"
	config += `	depends_on = [nxos_dme.PreReq0, ]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_svi_interfaces" "test" {
	depends_on = [nxos_svi_interfaces.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
