// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosSystem(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "name", "LEAF1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "mtu", "9216"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "default_admin_state", "up"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "admin_link_down_syslog_level", "4"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "admin_link_up_syslog_level", "4"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "admin_state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "allow_unsupported_sfp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "chassis_infrastructure_adaptor_vlan", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "chassis_infrastructure_epds_port_number", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "chassis_infrastructure_ipv6_address", "2001:db8::1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "chassis_infrastructure_vlan", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "chassis_management_instance", "mgmt0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "chassis_management_instance_fabric_number", "LeftFabric"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "control", "stateful-ha"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "interface_syslog_info", "info-1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "log_event", "linkStatusEnable"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "default_layer", "Layer3"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "system_interface_admin_state", "up"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "system_link_failure_laser_on", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "system_storm_control_multi_threshold", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_system.test", "vlan_tag_native", "false"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosSystemConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosSystemConfig() string {
	config := `resource "nxos_system" "test" {` + "\n"
	config += `	name = "LEAF1"` + "\n"
	config += `	mtu = 9216` + "\n"
	config += `	default_admin_state = "up"` + "\n"
	config += `	admin_link_down_syslog_level = 4` + "\n"
	config += `	admin_link_up_syslog_level = 4` + "\n"
	config += `	admin_state = "enabled"` + "\n"
	config += `	allow_unsupported_sfp = true` + "\n"
	config += `	chassis_infrastructure_adaptor_vlan = 100` + "\n"
	config += `	chassis_infrastructure_epds_port_number = 100` + "\n"
	config += `	chassis_infrastructure_ipv6_address = "2001:db8::1"` + "\n"
	config += `	chassis_infrastructure_vlan = 100` + "\n"
	config += `	chassis_management_instance = "mgmt0"` + "\n"
	config += `	chassis_management_instance_fabric_number = "LeftFabric"` + "\n"
	config += `	control = "stateful-ha"` + "\n"
	config += `	interface_syslog_info = "info-1"` + "\n"
	config += `	log_event = "linkStatusEnable"` + "\n"
	config += `	default_layer = "Layer3"` + "\n"
	config += `	system_interface_admin_state = "up"` + "\n"
	config += `	system_link_failure_laser_on = false` + "\n"
	config += `	system_storm_control_multi_threshold = false` + "\n"
	config += `	vlan_tag_native = false` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_system" "test" {
	depends_on = [nxos_system.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
