// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosPIMStaticRPGroupList(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim_static_rp_group_list.test", "address", "224.0.0.0/4"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim_static_rp_group_list.test", "bidir", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_pim_static_rp_group_list.test", "override", "true"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosPIMStaticRPGroupListPrerequisitesConfig + testAccDataSourceNxosPIMStaticRPGroupListConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceNxosPIMStaticRPGroupListPrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/fm/pim"
  class_name = "fmPim"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

resource "nxos_rest" "PreReq1" {
  dn = "sys/pim"
  class_name = "pimEntity"
  depends_on = [nxos_rest.PreReq0, ]
}

resource "nxos_rest" "PreReq2" {
  dn = "sys/pim/inst"
  class_name = "pimInst"
  depends_on = [nxos_rest.PreReq1, ]
}

resource "nxos_rest" "PreReq3" {
  dn = "sys/pim/inst/dom-[default]"
  class_name = "pimDom"
  content = {
      name = "default"
  }
  depends_on = [nxos_rest.PreReq2, ]
}

resource "nxos_rest" "PreReq4" {
  dn = "sys/pim/inst/dom-[default]/staticrp"
  class_name = "pimStaticRPP"
  depends_on = [nxos_rest.PreReq3, ]
}

resource "nxos_rest" "PreReq5" {
  dn = "sys/pim/inst/dom-[default]/staticrp/rp-[1.2.3.4]"
  class_name = "pimStaticRP"
  content = {
      addr = "1.2.3.4"
  }
  depends_on = [nxos_rest.PreReq4, ]
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosPIMStaticRPGroupListConfig() string {
	config := `resource "nxos_pim_static_rp_group_list" "test" {` + "\n"
	config += `	vrf_name = "default"` + "\n"
	config += `	rp_address = "1.2.3.4"` + "\n"
	config += `	address = "224.0.0.0/4"` + "\n"
	config += `	bidir = true` + "\n"
	config += `	override = true` + "\n"
	config += `	depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, nxos_rest.PreReq3, nxos_rest.PreReq4, nxos_rest.PreReq5, ]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_pim_static_rp_group_list" "test" {
	vrf_name = "default"
	rp_address = "1.2.3.4"
	address = "224.0.0.0/4"
	depends_on = [nxos_pim_static_rp_group_list.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
