// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource
func TestAccDataSourceNxosPTP(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "domain_number", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_grandmaster_change", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_parent_change", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "peer_delay_request_interval", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "priority1", "128"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "priority2", "128"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "using_system_clock", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "source_ip", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "vrf_name", "default"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_high_correction_interval", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_high_correction", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_high_correction_periodic", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_port_state_change_category", "all"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_port_state_change_interval", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_port_state_change", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "notify_port_state_change_periodic", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.announce_interval_value", "2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.announce_timeout_value", "3"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.delay_request_min_interval_value", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.negotiation_schema", "schema1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.ptp", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.role", "master"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.sync_interval_value", "-1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.transmission", "multicast"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.transport", "ipv4"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.unicast_source", "10.2.2.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.unicast_vrf", "default"))
	checks = append(checks, resource.TestCheckResourceAttr("data.nxos_ptp.test", "interfaces.eth1/1.peers.10.1.1.2.negotiation_schema", "schema1"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNxosPTPPrerequisitesConfig + testAccDataSourceNxosPTPConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceNxosPTPPrerequisitesConfig = `
resource "nxos_dme" "PreReq0" {
  dn = "sys/fm/ptp"
  class_name = "fmPtp"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig
func testAccDataSourceNxosPTPConfig() string {
	config := `resource "nxos_ptp" "test" {` + "\n"
	config += `	domain_number = 1` + "\n"
	config += `	notify_grandmaster_change = "enabled"` + "\n"
	config += `	notify_parent_change = "enabled"` + "\n"
	config += `	peer_delay_request_interval = 1` + "\n"
	config += `	priority1 = 128` + "\n"
	config += `	priority2 = 128` + "\n"
	config += `	using_system_clock = true` + "\n"
	config += `	source_ip = "10.1.1.1"` + "\n"
	config += `	vrf_name = "default"` + "\n"
	config += `	domains = {` + "\n"
	config += `		"1" = {` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	notify_high_correction_interval = 10` + "\n"
	config += `	notify_high_correction = "enabled"` + "\n"
	config += `	notify_high_correction_periodic = "enabled"` + "\n"
	config += `	notify_port_state_change_category = "all"` + "\n"
	config += `	notify_port_state_change_interval = 10` + "\n"
	config += `	notify_port_state_change = "enabled"` + "\n"
	config += `	notify_port_state_change_periodic = "enabled"` + "\n"
	config += `	interfaces = {` + "\n"
	config += `		"eth1/1" = {` + "\n"
	config += `			announce_interval_value = 2` + "\n"
	config += `			announce_timeout_value = 3` + "\n"
	config += `			delay_request_min_interval_value = 0` + "\n"
	config += `			negotiation_schema = "schema1"` + "\n"
	config += `			ptp = true` + "\n"
	config += `			role = "master"` + "\n"
	config += `			sync_interval_value = -1` + "\n"
	config += `			transmission = "multicast"` + "\n"
	config += `			transport = "ipv4"` + "\n"
	config += `			unicast_source = "10.2.2.1"` + "\n"
	config += `			unicast_vrf = "default"` + "\n"
	config += `			peers = {` + "\n"
	config += `				"10.1.1.2" = {` + "\n"
	config += `					negotiation_schema = "schema1"` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	depends_on = [nxos_dme.PreReq0, ]` + "\n"
	config += `}` + "\n"

	config += `
data "nxos_ptp" "test" {
	depends_on = [nxos_ptp.test]
}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
