// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types

type IPv4PrefixList struct {
	Device  types.String            `tfsdk:"device"`
	Dn      types.String            `tfsdk:"id"`
	Name    types.String            `tfsdk:"name"`
	Entries []IPv4PrefixListEntries `tfsdk:"entries"`
}

type IPv4PrefixListEntries struct {
	Order     types.Int64  `tfsdk:"order"`
	Action    types.String `tfsdk:"action"`
	Criteria  types.String `tfsdk:"criteria"`
	Prefix    types.String `tfsdk:"prefix"`
	FromRange types.Int64  `tfsdk:"from_range"`
	ToRange   types.Int64  `tfsdk:"to_range"`
}

type IPv4PrefixListIdentity struct {
	Device types.String `tfsdk:"device"`
	Name   types.String `tfsdk:"name"`
}

func (data *IPv4PrefixListIdentity) toIdentity(ctx context.Context, plan *IPv4PrefixList) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
	data.Name = plan.Name
}

func (data *IPv4PrefixList) fromIdentity(ctx context.Context, identity *IPv4PrefixListIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
	data.Name = identity.Name
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data IPv4PrefixList) getDn() string {
	return fmt.Sprintf("sys/rpm/pfxlistv4-[%s]", data.Name.ValueString())
}

func (data IPv4PrefixListEntries) getRn() string {
	return fmt.Sprintf("ent-%v", data.Order.ValueInt64())
}

func (data IPv4PrefixList) getClassName() string {
	return "rtpfxRuleV4"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data IPv4PrefixList) toBody() nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	if (!data.Name.IsUnknown() && !data.Name.IsNull()) || false {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"name", data.Name.ValueString())
	}
	var attrs string
	childrenPath := data.getClassName() + ".children"
	for _, child := range data.Entries {
		attrs = "{}"
		if (!child.Order.IsUnknown() && !child.Order.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "order", strconv.FormatInt(child.Order.ValueInt64(), 10))
		}
		if (!child.Action.IsUnknown() && !child.Action.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "action", child.Action.ValueString())
		}
		if (!child.Criteria.IsUnknown() && !child.Criteria.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "criteria", child.Criteria.ValueString())
		}
		if (!child.Prefix.IsUnknown() && !child.Prefix.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "pfx", child.Prefix.ValueString())
		}
		if (!child.FromRange.IsUnknown() && !child.FromRange.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "fromPfxLen", strconv.FormatInt(child.FromRange.ValueInt64(), 10))
		}
		if (!child.ToRange.IsUnknown() && !child.ToRange.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "toPfxLen", strconv.FormatInt(child.ToRange.ValueInt64(), 10))
		}
		body, _ = sjson.SetRaw(body, childrenPath+".-1.rtpfxEntry.attributes", attrs)
	}

	return nxos.Body{body}
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *IPv4PrefixList) fromBody(res gjson.Result) {
	data.Name = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	res.Get(data.getClassName() + ".children").ForEach(
		func(_, v gjson.Result) bool {
			v.ForEach(
				func(classname, value gjson.Result) bool {
					if classname.String() == "rtpfxEntry" {
						var child IPv4PrefixListEntries
						child.Order = types.Int64Value(value.Get("attributes.order").Int())
						child.Action = types.StringValue(value.Get("attributes.action").String())
						child.Criteria = types.StringValue(value.Get("attributes.criteria").String())
						child.Prefix = types.StringValue(value.Get("attributes.pfx").String())
						child.FromRange = types.Int64Value(value.Get("attributes.fromPfxLen").Int())
						child.ToRange = types.Int64Value(value.Get("attributes.toPfxLen").Int())
						data.Entries = append(data.Entries, child)
					}
					return true
				},
			)
			return true
		},
	)
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *IPv4PrefixList) updateFromBody(res gjson.Result) {
	if !data.Name.IsNull() {
		data.Name = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	} else {
		data.Name = types.StringNull()
	}
	for c := range data.Entries {
		var rrtpfxEntry gjson.Result
		res.Get(data.getClassName() + ".children").ForEach(
			func(_, v gjson.Result) bool {
				key := v.Get("rtpfxEntry.attributes.rn").String()
				if key == data.Entries[c].getRn() {
					rrtpfxEntry = v
					return false
				}
				return true
			},
		)
		if !data.Entries[c].Order.IsNull() {
			data.Entries[c].Order = types.Int64Value(rrtpfxEntry.Get("rtpfxEntry.attributes.order").Int())
		} else {
			data.Entries[c].Order = types.Int64Null()
		}
		if !data.Entries[c].Action.IsNull() {
			data.Entries[c].Action = types.StringValue(rrtpfxEntry.Get("rtpfxEntry.attributes.action").String())
		} else {
			data.Entries[c].Action = types.StringNull()
		}
		if !data.Entries[c].Criteria.IsNull() {
			data.Entries[c].Criteria = types.StringValue(rrtpfxEntry.Get("rtpfxEntry.attributes.criteria").String())
		} else {
			data.Entries[c].Criteria = types.StringNull()
		}
		if !data.Entries[c].Prefix.IsNull() {
			data.Entries[c].Prefix = types.StringValue(rrtpfxEntry.Get("rtpfxEntry.attributes.pfx").String())
		} else {
			data.Entries[c].Prefix = types.StringNull()
		}
		if !data.Entries[c].FromRange.IsNull() {
			data.Entries[c].FromRange = types.Int64Value(rrtpfxEntry.Get("rtpfxEntry.attributes.fromPfxLen").Int())
		} else {
			data.Entries[c].FromRange = types.Int64Null()
		}
		if !data.Entries[c].ToRange.IsNull() {
			data.Entries[c].ToRange = types.Int64Value(rrtpfxEntry.Get("rtpfxEntry.attributes.toPfxLen").Int())
		} else {
			data.Entries[c].ToRange = types.Int64Null()
		}
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin toDeleteBody

func (data IPv4PrefixList) toDeleteBody() nxos.Body {
	body := ""

	return nxos.Body{body}
}

// End of section. //template:end toDeleteBody

// Section below is generated&owned by "gen/generator.go". //template:begin getDeleteDns

func (data IPv4PrefixList) getDeleteDns() []string {
	dns := []string{}
	dns = append(dns, data.getDn())

	return dns
}

// End of section. //template:end getDeleteDns

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

func (data IPv4PrefixList) getDeletedItems(ctx context.Context, state IPv4PrefixList) []string {
	deletedItems := []string{}
	for _, stateChild := range state.Entries {
		found := false
		for _, planChild := range data.Entries {
			if stateChild.Order == planChild.Order {
				found = true
				break
			}
		}
		if !found {
			deletedItems = append(deletedItems, data.getDn()+"/"+stateChild.getRn())
		}
	}
	return deletedItems
}

// End of section. //template:end getDeletedItems
