// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports

import (
	"context"
	"fmt"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-nxos/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types

type VRF struct {
	Device types.String       `tfsdk:"device"`
	Dn     types.String       `tfsdk:"id"`
	Vrfs   map[string]VRFVrfs `tfsdk:"vrfs"`
}

type VRFVrfs struct {
	Description        types.String                      `tfsdk:"description"`
	AdminState         types.String                      `tfsdk:"admin_state"`
	ControllerId       types.Int64                       `tfsdk:"controller_id"`
	Encap              types.String                      `tfsdk:"encap"`
	L3vni              types.Bool                        `tfsdk:"l3vni"`
	Oui                types.String                      `tfsdk:"oui"`
	VpnId              types.String                      `tfsdk:"vpn_id"`
	RoutingEncap       types.String                      `tfsdk:"routing_encap"`
	RouteDistinguisher types.String                      `tfsdk:"route_distinguisher"`
	AddressFamilies    map[string]VRFVrfsAddressFamilies `tfsdk:"address_families"`
}

type VRFVrfsAddressFamilies struct {
	RouteTargetAddressFamilies map[string]VRFVrfsAddressFamiliesRouteTargetAddressFamilies `tfsdk:"route_target_address_families"`
}

type VRFVrfsAddressFamiliesRouteTargetAddressFamilies struct {
	RouteTargetDirections map[string]VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirections `tfsdk:"route_target_directions"`
}

type VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirections struct {
	RouteTargets map[string]VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirectionsRouteTargets `tfsdk:"route_targets"`
}

type VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirectionsRouteTargets struct {
}

type VRFIdentity struct {
	Device types.String `tfsdk:"device"`
}

func (data *VRFIdentity) toIdentity(ctx context.Context, plan *VRF) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
}

func (data *VRF) fromIdentity(ctx context.Context, identity *VRFIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data VRF) getDn() string {
	return "sys"
}

func (data VRFVrfs) getRn(key string) string {
	return fmt.Sprintf("inst-[%s]", key)
}

func (data VRFVrfsAddressFamilies) getRn(key string) string {
	return fmt.Sprintf("af-[%s]", key)
}

func (data VRFVrfsAddressFamiliesRouteTargetAddressFamilies) getRn(key string) string {
	return fmt.Sprintf("ctrl-[%s]", key)
}

func (data VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirections) getRn(key string) string {
	return fmt.Sprintf("rttp-%s", key)
}

func (data VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirectionsRouteTargets) getRn(key string) string {
	return fmt.Sprintf("ent-[%s]", key)
}

func (data VRF) getClassName() string {
	return "topSystem"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data VRF) toBody(config VRF) nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	var attrs string
	childrenPath := data.getClassName() + ".children"
	for key, child := range data.Vrfs {
		configChild, configChildOk := config.Vrfs[key]
		_ = configChild
		_ = configChildOk
		attrs = "{}"
		attrs, _ = sjson.Set(attrs, "name", key)
		if configChildOk && !child.Description.IsUnknown() && !child.Description.IsNull() && !configChild.Description.IsNull() {
			attrs, _ = sjson.Set(attrs, "descr", child.Description.ValueString())
		}
		if configChildOk && !child.AdminState.IsUnknown() && !child.AdminState.IsNull() && !configChild.AdminState.IsNull() {
			attrs, _ = sjson.Set(attrs, "adminState", child.AdminState.ValueString())
		}
		if configChildOk && !child.ControllerId.IsUnknown() && !child.ControllerId.IsNull() && !configChild.ControllerId.IsNull() {
			attrs, _ = sjson.Set(attrs, "ctrlrId", strconv.FormatInt(child.ControllerId.ValueInt64(), 10))
		}
		if configChildOk && !child.Encap.IsUnknown() && !child.Encap.IsNull() && !configChild.Encap.IsNull() {
			attrs, _ = sjson.Set(attrs, "encap", child.Encap.ValueString())
		}
		if configChildOk && !child.L3vni.IsUnknown() && !child.L3vni.IsNull() && !configChild.L3vni.IsNull() {
			attrs, _ = sjson.Set(attrs, "l3vni", strconv.FormatBool(child.L3vni.ValueBool()))
		}
		if configChildOk && !child.Oui.IsUnknown() && !child.Oui.IsNull() && !configChild.Oui.IsNull() {
			attrs, _ = sjson.Set(attrs, "oui", child.Oui.ValueString())
		}
		if configChildOk && !child.VpnId.IsUnknown() && !child.VpnId.IsNull() && !configChild.VpnId.IsNull() {
			attrs, _ = sjson.Set(attrs, "vpnId", child.VpnId.ValueString())
		}
		body, _ = sjson.SetRaw(body, childrenPath+".-1.l3Inst.attributes", attrs)
		{
			nestedIndex := len(gjson.Get(body, childrenPath).Array()) - 1
			nestedChildrenPath := childrenPath + "." + strconv.Itoa(nestedIndex) + ".l3Inst.children"
			{
				attrs = "{}"
				attrs, _ = sjson.Set(attrs, "name", key)
				if !child.RoutingEncap.IsUnknown() && !child.RoutingEncap.IsNull() && !configChild.RoutingEncap.IsNull() {
					attrs, _ = sjson.Set(attrs, "encap", child.RoutingEncap.ValueString())
				}
				if !child.RouteDistinguisher.IsUnknown() && !child.RouteDistinguisher.IsNull() && !configChild.RouteDistinguisher.IsNull() {
					attrs, _ = sjson.Set(attrs, "rd", child.RouteDistinguisher.ValueString())
				}
				childIndex := len(gjson.Get(body, nestedChildrenPath).Array())
				childBodyPath := nestedChildrenPath + "." + strconv.Itoa(childIndex) + ".rtctrlDom"
				body, _ = sjson.SetRaw(body, childBodyPath+".attributes", attrs)
				nestedChildrenPath := childBodyPath + ".children"
				for key, child := range child.AddressFamilies {
					configChild, configChildOk := configChild.AddressFamilies[key]
					_ = configChild
					_ = configChildOk
					attrs = "{}"
					attrs, _ = sjson.Set(attrs, "type", key)
					body, _ = sjson.SetRaw(body, nestedChildrenPath+".-1.rtctrlDomAf.attributes", attrs)
					{
						nestedIndex := len(gjson.Get(body, nestedChildrenPath).Array()) - 1
						nestedChildrenPath := nestedChildrenPath + "." + strconv.Itoa(nestedIndex) + ".rtctrlDomAf.children"
						for key, child := range child.RouteTargetAddressFamilies {
							configChild, configChildOk := configChild.RouteTargetAddressFamilies[key]
							_ = configChild
							_ = configChildOk
							attrs = "{}"
							attrs, _ = sjson.Set(attrs, "type", key)
							body, _ = sjson.SetRaw(body, nestedChildrenPath+".-1.rtctrlAfCtrl.attributes", attrs)
							{
								nestedIndex := len(gjson.Get(body, nestedChildrenPath).Array()) - 1
								nestedChildrenPath := nestedChildrenPath + "." + strconv.Itoa(nestedIndex) + ".rtctrlAfCtrl.children"
								for key, child := range child.RouteTargetDirections {
									configChild, configChildOk := configChild.RouteTargetDirections[key]
									_ = configChild
									_ = configChildOk
									attrs = "{}"
									attrs, _ = sjson.Set(attrs, "type", key)
									body, _ = sjson.SetRaw(body, nestedChildrenPath+".-1.rtctrlRttP.attributes", attrs)
									{
										nestedIndex := len(gjson.Get(body, nestedChildrenPath).Array()) - 1
										nestedChildrenPath := nestedChildrenPath + "." + strconv.Itoa(nestedIndex) + ".rtctrlRttP.children"
										for key := range child.RouteTargets {
											configChild, configChildOk := configChild.RouteTargets[key]
											_ = configChild
											_ = configChildOk
											attrs = "{}"
											attrs, _ = sjson.Set(attrs, "rtt", key)
											body, _ = sjson.SetRaw(body, nestedChildrenPath+".-1.rtctrlRttEntry.attributes", attrs)
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}

	return nxos.Body{Str: body}
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *VRF) fromBody(res gjson.Result) {
	res.Get(data.getClassName() + ".children").ForEach(
		func(_, v gjson.Result) bool {
			v.ForEach(
				func(classname, value gjson.Result) bool {
					if classname.String() == "l3Inst" {
						var child VRFVrfs
						child.Description = types.StringValue(value.Get("attributes.descr").String())
						child.AdminState = types.StringValue(value.Get("attributes.adminState").String())
						child.ControllerId = types.Int64Value(value.Get("attributes.ctrlrId").Int())
						child.Encap = types.StringValue(value.Get("attributes.encap").String())
						child.L3vni = types.BoolValue(helpers.ParseNxosBoolean(value.Get("attributes.l3vni").String()))
						child.Oui = types.StringValue(value.Get("attributes.oui").String())
						child.VpnId = types.StringValue(value.Get("attributes.vpnId").String())
						mapKey := value.Get("attributes.name").String()
						{
							var rrtctrlDom gjson.Result
							value.Get("children").ForEach(
								func(_, nestedV gjson.Result) bool {
									rnValue := nestedV.Get("rtctrlDom.attributes.rn").String()
									if rnValue == fmt.Sprintf("dom-%[1]s", mapKey) {
										rrtctrlDom = nestedV
										return false
									}
									return true
								},
							)
							child.RoutingEncap = types.StringValue(rrtctrlDom.Get("rtctrlDom.attributes.encap").String())
							child.RouteDistinguisher = types.StringValue(rrtctrlDom.Get("rtctrlDom.attributes.rd").String())
							rrtctrlDom.Get("rtctrlDom").Get("children").ForEach(
								func(_, nestedV gjson.Result) bool {
									nestedV.ForEach(
										func(nestedClassname, nestedValue gjson.Result) bool {
											if nestedClassname.String() == "rtctrlDomAf" {
												var nestedChildrtctrlDomAf VRFVrfsAddressFamilies
												nestedMapKey := nestedValue.Get("attributes.type").String()
												nestedValue.Get("children").ForEach(
													func(_, nestedV gjson.Result) bool {
														nestedV.ForEach(
															func(nestedClassname, nestedValue gjson.Result) bool {
																if nestedClassname.String() == "rtctrlAfCtrl" {
																	var nestedChildrtctrlAfCtrl VRFVrfsAddressFamiliesRouteTargetAddressFamilies
																	nestedMapKey := nestedValue.Get("attributes.type").String()
																	nestedValue.Get("children").ForEach(
																		func(_, nestedV gjson.Result) bool {
																			nestedV.ForEach(
																				func(nestedClassname, nestedValue gjson.Result) bool {
																					if nestedClassname.String() == "rtctrlRttP" {
																						var nestedChildrtctrlRttP VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirections
																						nestedMapKey := nestedValue.Get("attributes.type").String()
																						nestedValue.Get("children").ForEach(
																							func(_, nestedV gjson.Result) bool {
																								nestedV.ForEach(
																									func(nestedClassname, nestedValue gjson.Result) bool {
																										if nestedClassname.String() == "rtctrlRttEntry" {
																											var nestedChildrtctrlRttEntry VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirectionsRouteTargets
																											nestedMapKey := nestedValue.Get("attributes.rtt").String()
																											if nestedChildrtctrlRttP.RouteTargets == nil {
																												nestedChildrtctrlRttP.RouteTargets = make(map[string]VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirectionsRouteTargets)
																											}
																											nestedChildrtctrlRttP.RouteTargets[nestedMapKey] = nestedChildrtctrlRttEntry
																										}
																										return true
																									},
																								)
																								return true
																							},
																						)
																						if nestedChildrtctrlAfCtrl.RouteTargetDirections == nil {
																							nestedChildrtctrlAfCtrl.RouteTargetDirections = make(map[string]VRFVrfsAddressFamiliesRouteTargetAddressFamiliesRouteTargetDirections)
																						}
																						nestedChildrtctrlAfCtrl.RouteTargetDirections[nestedMapKey] = nestedChildrtctrlRttP
																					}
																					return true
																				},
																			)
																			return true
																		},
																	)
																	if nestedChildrtctrlDomAf.RouteTargetAddressFamilies == nil {
																		nestedChildrtctrlDomAf.RouteTargetAddressFamilies = make(map[string]VRFVrfsAddressFamiliesRouteTargetAddressFamilies)
																	}
																	nestedChildrtctrlDomAf.RouteTargetAddressFamilies[nestedMapKey] = nestedChildrtctrlAfCtrl
																}
																return true
															},
														)
														return true
													},
												)
												if child.AddressFamilies == nil {
													child.AddressFamilies = make(map[string]VRFVrfsAddressFamilies)
												}
												child.AddressFamilies[nestedMapKey] = nestedChildrtctrlDomAf
											}
											return true
										},
									)
									return true
								},
							)
						}
						if data.Vrfs == nil {
							data.Vrfs = make(map[string]VRFVrfs)
						}
						data.Vrfs[mapKey] = child
					}
					return true
				},
			)
			return true
		},
	)
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *VRF) updateFromBody(res gjson.Result) {
	for key, item := range data.Vrfs {
		var rl3Inst gjson.Result
		res.Get(data.getClassName() + ".children").ForEach(
			func(_, v gjson.Result) bool {
				if v.Get("l3Inst.attributes.name").String() == key {
					rl3Inst = v
					return false
				}
				return true
			},
		)
		if !rl3Inst.Exists() {
			delete(data.Vrfs, key)
			continue
		}
		if !item.Description.IsNull() {
			item.Description = types.StringValue(rl3Inst.Get("l3Inst.attributes.descr").String())
		} else {
			item.Description = types.StringNull()
		}
		if !item.AdminState.IsNull() {
			item.AdminState = types.StringValue(rl3Inst.Get("l3Inst.attributes.adminState").String())
		} else {
			item.AdminState = types.StringNull()
		}
		if !item.ControllerId.IsNull() {
			item.ControllerId = types.Int64Value(rl3Inst.Get("l3Inst.attributes.ctrlrId").Int())
		} else {
			item.ControllerId = types.Int64Null()
		}
		if !item.Encap.IsNull() {
			item.Encap = types.StringValue(rl3Inst.Get("l3Inst.attributes.encap").String())
		} else {
			item.Encap = types.StringNull()
		}
		if !item.L3vni.IsNull() {
			item.L3vni = types.BoolValue(helpers.ParseNxosBoolean(rl3Inst.Get("l3Inst.attributes.l3vni").String()))
		} else {
			item.L3vni = types.BoolNull()
		}
		if !item.Oui.IsNull() {
			item.Oui = types.StringValue(rl3Inst.Get("l3Inst.attributes.oui").String())
		} else {
			item.Oui = types.StringNull()
		}
		if !item.VpnId.IsNull() {
			item.VpnId = types.StringValue(rl3Inst.Get("l3Inst.attributes.vpnId").String())
		} else {
			item.VpnId = types.StringNull()
		}
		{
			var rrtctrlDom gjson.Result
			rl3Inst.Get("l3Inst.children").ForEach(
				func(_, v gjson.Result) bool {
					rnValue := v.Get("rtctrlDom.attributes.rn").String()
					if rnValue == fmt.Sprintf("dom-%[1]s", key) {
						rrtctrlDom = v
						return false
					}
					return true
				},
			)
			if !item.RoutingEncap.IsNull() {
				item.RoutingEncap = types.StringValue(rrtctrlDom.Get("rtctrlDom.attributes.encap").String())
			} else {
				item.RoutingEncap = types.StringNull()
			}
			if !item.RouteDistinguisher.IsNull() {
				item.RouteDistinguisher = types.StringValue(rrtctrlDom.Get("rtctrlDom.attributes.rd").String())
			} else {
				item.RouteDistinguisher = types.StringNull()
			}
			for nc := range item.AddressFamilies {
				ncItem := item.AddressFamilies[nc]
				var rrtctrlDomAf gjson.Result
				rrtctrlDom.Get("rtctrlDom.children").ForEach(
					func(_, v gjson.Result) bool {
						if v.Get("rtctrlDomAf.attributes.type").String() == nc {
							rrtctrlDomAf = v
							return false
						}
						return true
					},
				)
				if !rrtctrlDomAf.Exists() {
					delete(item.AddressFamilies, nc)
					continue
				}
				for nc_ := range ncItem.RouteTargetAddressFamilies {
					nc_Item := ncItem.RouteTargetAddressFamilies[nc_]
					var rrtctrlAfCtrl gjson.Result
					rrtctrlDomAf.Get("rtctrlDomAf.children").ForEach(
						func(_, v gjson.Result) bool {
							if v.Get("rtctrlAfCtrl.attributes.type").String() == nc_ {
								rrtctrlAfCtrl = v
								return false
							}
							return true
						},
					)
					if !rrtctrlAfCtrl.Exists() {
						delete(ncItem.RouteTargetAddressFamilies, nc_)
						continue
					}
					for nc__ := range nc_Item.RouteTargetDirections {
						nc__Item := nc_Item.RouteTargetDirections[nc__]
						var rrtctrlRttP gjson.Result
						rrtctrlAfCtrl.Get("rtctrlAfCtrl.children").ForEach(
							func(_, v gjson.Result) bool {
								if v.Get("rtctrlRttP.attributes.type").String() == nc__ {
									rrtctrlRttP = v
									return false
								}
								return true
							},
						)
						if !rrtctrlRttP.Exists() {
							delete(nc_Item.RouteTargetDirections, nc__)
							continue
						}
						for nc___ := range nc__Item.RouteTargets {
							nc___Item := nc__Item.RouteTargets[nc___]
							var rrtctrlRttEntry gjson.Result
							rrtctrlRttP.Get("rtctrlRttP.children").ForEach(
								func(_, v gjson.Result) bool {
									if v.Get("rtctrlRttEntry.attributes.rtt").String() == nc___ {
										rrtctrlRttEntry = v
										return false
									}
									return true
								},
							)
							if !rrtctrlRttEntry.Exists() {
								delete(nc__Item.RouteTargets, nc___)
								continue
							}
							nc__Item.RouteTargets[nc___] = nc___Item
						}
						nc_Item.RouteTargetDirections[nc__] = nc__Item
					}
					ncItem.RouteTargetAddressFamilies[nc_] = nc_Item
				}
				item.AddressFamilies[nc] = ncItem
			}
		}
		data.Vrfs[key] = item
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin toDeleteBody

func (data VRF) toDeleteBody() nxos.Body {
	body := ""
	if body == "" {
		body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	}
	childrenPath := data.getClassName() + ".children"
	for key, child := range data.Vrfs {
		deleteBody := ""
		deleteBody, _ = sjson.Set(deleteBody, "l3Inst.attributes.rn", child.getRn(key))
		deleteBody, _ = sjson.Set(deleteBody, "l3Inst.attributes.status", "deleted")
		body, _ = sjson.SetRaw(body, childrenPath+".-1", deleteBody)
	}

	return nxos.Body{Str: body}
}

func (data VRF) toBodyWithDeletes(ctx context.Context, state VRF, config VRF) nxos.Body {
	body := data.toBody(config)
	bodyPath := data.getClassName() + ".children"
	_ = bodyPath
	for stateKey := range state.Vrfs {
		if _, found := data.Vrfs[stateKey]; !found {
			stateChild := state.Vrfs[stateKey]
			deleteBody := ""
			deleteBody, _ = sjson.Set(deleteBody, "l3Inst.attributes.rn", stateChild.getRn(stateKey))
			deleteBody, _ = sjson.Set(deleteBody, "l3Inst.attributes.status", "deleted")
			body.Str, _ = sjson.SetRaw(body.Str, bodyPath+".-1", deleteBody)
		}
	}
	for di := range state.Vrfs {
		if _, found := data.Vrfs[di]; !found {
			continue
		}
		stateItemdi := state.Vrfs[di]
		planItemdi := data.Vrfs[di]
		matchBodyPathdi := ""
		for mi, mv := range gjson.Get(body.Str, bodyPath).Array() {
			if mv.Get("l3Inst.attributes.rn").String() == stateItemdi.getRn(di) {
				matchBodyPathdi = bodyPath + "." + strconv.Itoa(mi) + ".l3Inst.children"
				break
			}
		}
		if matchBodyPathdi == "" {
			continue
		}
		for stateKey := range stateItemdi.AddressFamilies {
			if _, found := planItemdi.AddressFamilies[stateKey]; !found {
				stateChild := stateItemdi.AddressFamilies[stateKey]
				deleteBody := ""
				deleteBody, _ = sjson.Set(deleteBody, "rtctrlDomAf.attributes.rn", stateChild.getRn(stateKey))
				deleteBody, _ = sjson.Set(deleteBody, "rtctrlDomAf.attributes.status", "deleted")
				body.Str, _ = sjson.SetRaw(body.Str, matchBodyPathdi+".0.rtctrlDom.children"+".-1", deleteBody)
			}
		}
		for di__ := range stateItemdi.AddressFamilies {
			if _, found := planItemdi.AddressFamilies[di__]; !found {
				continue
			}
			stateItemdi__ := stateItemdi.AddressFamilies[di__]
			planItemdi__ := planItemdi.AddressFamilies[di__]
			matchBodyPathdi__ := ""
			for mi, mv := range gjson.Get(body.Str, matchBodyPathdi+".0.rtctrlDom.children").Array() {
				if mv.Get("rtctrlDomAf.attributes.rn").String() == stateItemdi__.getRn(di__) {
					matchBodyPathdi__ = matchBodyPathdi + ".0.rtctrlDom.children" + "." + strconv.Itoa(mi) + ".rtctrlDomAf.children"
					break
				}
			}
			if matchBodyPathdi__ == "" {
				continue
			}
			for stateChildKey := range stateItemdi__.RouteTargetAddressFamilies {
				if _, found := planItemdi__.RouteTargetAddressFamilies[stateChildKey]; !found {
					stateChild := stateItemdi__.RouteTargetAddressFamilies[stateChildKey]
					deleteBody := ""
					deleteBody, _ = sjson.Set(deleteBody, "rtctrlAfCtrl.attributes.rn", stateChild.getRn(stateChildKey))
					deleteBody, _ = sjson.Set(deleteBody, "rtctrlAfCtrl.attributes.status", "deleted")
					body.Str, _ = sjson.SetRaw(body.Str, matchBodyPathdi__+".-1", deleteBody)
				}
			}
			for di___ := range stateItemdi__.RouteTargetAddressFamilies {
				if _, found := planItemdi__.RouteTargetAddressFamilies[di___]; !found {
					continue
				}
				stateItemdi___ := stateItemdi__.RouteTargetAddressFamilies[di___]
				planItemdi___ := planItemdi__.RouteTargetAddressFamilies[di___]
				matchBodyPathdi___ := ""
				for mi, mv := range gjson.Get(body.Str, matchBodyPathdi__).Array() {
					if mv.Get("rtctrlAfCtrl.attributes.rn").String() == stateItemdi___.getRn(di___) {
						matchBodyPathdi___ = matchBodyPathdi__ + "." + strconv.Itoa(mi) + ".rtctrlAfCtrl.children"
						break
					}
				}
				if matchBodyPathdi___ == "" {
					continue
				}
				for stateChildKey := range stateItemdi___.RouteTargetDirections {
					if _, found := planItemdi___.RouteTargetDirections[stateChildKey]; !found {
						stateChild := stateItemdi___.RouteTargetDirections[stateChildKey]
						deleteBody := ""
						deleteBody, _ = sjson.Set(deleteBody, "rtctrlRttP.attributes.rn", stateChild.getRn(stateChildKey))
						deleteBody, _ = sjson.Set(deleteBody, "rtctrlRttP.attributes.status", "deleted")
						body.Str, _ = sjson.SetRaw(body.Str, matchBodyPathdi___+".-1", deleteBody)
					}
				}
				for di____ := range stateItemdi___.RouteTargetDirections {
					if _, found := planItemdi___.RouteTargetDirections[di____]; !found {
						continue
					}
					stateItemdi____ := stateItemdi___.RouteTargetDirections[di____]
					planItemdi____ := planItemdi___.RouteTargetDirections[di____]
					matchBodyPathdi____ := ""
					for mi, mv := range gjson.Get(body.Str, matchBodyPathdi___).Array() {
						if mv.Get("rtctrlRttP.attributes.rn").String() == stateItemdi____.getRn(di____) {
							matchBodyPathdi____ = matchBodyPathdi___ + "." + strconv.Itoa(mi) + ".rtctrlRttP.children"
							break
						}
					}
					if matchBodyPathdi____ == "" {
						continue
					}
					for stateChildKey := range stateItemdi____.RouteTargets {
						if _, found := planItemdi____.RouteTargets[stateChildKey]; !found {
							stateChild := stateItemdi____.RouteTargets[stateChildKey]
							deleteBody := ""
							deleteBody, _ = sjson.Set(deleteBody, "rtctrlRttEntry.attributes.rn", stateChild.getRn(stateChildKey))
							deleteBody, _ = sjson.Set(deleteBody, "rtctrlRttEntry.attributes.status", "deleted")
							body.Str, _ = sjson.SetRaw(body.Str, matchBodyPathdi____+".-1", deleteBody)
						}
					}
				}
			}
		}
	}
	return body
}

// End of section. //template:end toDeleteBody
