// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type IPv6VRF struct {
	Device types.String `tfsdk:"device"`
	Dn     types.String `tfsdk:"id"`
	Name   types.String `tfsdk:"name"`
}

type IPv6VRFIdentity struct {
	Device types.String `tfsdk:"device"`
	Name   types.String `tfsdk:"name"`
}

func (data *IPv6VRFIdentity) toIdentity(ctx context.Context, plan *IPv6VRF) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
	data.Name = plan.Name
}

func (data *IPv6VRF) fromIdentity(ctx context.Context, identity *IPv6VRFIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
	data.Name = identity.Name
}

func (data IPv6VRF) getDn() string {
	return fmt.Sprintf("sys/ipv6/inst/dom-[%s]", data.Name.ValueString())
}

func (data IPv6VRF) getClassName() string {
	return "ipv6Dom"
}

func (data IPv6VRF) toBody(statusReplace bool) nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	if statusReplace {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"status", "replaced")
	}
	if (!data.Name.IsUnknown() && !data.Name.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"name", data.Name.ValueString())
	}

	return nxos.Body{body}
}

func (data *IPv6VRF) fromBody(res gjson.Result) {
	data.Name = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
}

func (data *IPv6VRF) updateFromBody(res gjson.Result) {
	if !data.Name.IsNull() {
		data.Name = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	} else {
		data.Name = types.StringNull()
	}
}

func (data IPv6VRF) toDeleteBody() nxos.Body {
	body := ""

	return nxos.Body{body}
}
