// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type BGPPeerTemplate struct {
	Device          types.String `tfsdk:"device"`
	Dn              types.String `tfsdk:"id"`
	Asn             types.String `tfsdk:"asn"`
	TemplateName    types.String `tfsdk:"template_name"`
	RemoteAsn       types.String `tfsdk:"remote_asn"`
	Description     types.String `tfsdk:"description"`
	PeerType        types.String `tfsdk:"peer_type"`
	SourceInterface types.String `tfsdk:"source_interface"`
}

type BGPPeerTemplateIdentity struct {
	Device       types.String `tfsdk:"device"`
	Asn          types.String `tfsdk:"asn"`
	TemplateName types.String `tfsdk:"template_name"`
}

func (data *BGPPeerTemplateIdentity) toIdentity(ctx context.Context, plan *BGPPeerTemplate) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
	data.Asn = plan.Asn
	data.TemplateName = plan.TemplateName
}

func (data *BGPPeerTemplate) fromIdentity(ctx context.Context, identity *BGPPeerTemplateIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
	data.Asn = identity.Asn
	data.TemplateName = identity.TemplateName
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath
func (data BGPPeerTemplate) getDn() string {
	return fmt.Sprintf("sys/bgp/inst/dom-[default]/peercont-[%s]", data.TemplateName.ValueString())
}

func (data BGPPeerTemplate) getClassName() string {
	return "bgpPeerCont"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody
func (data BGPPeerTemplate) toBody() nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	if (!data.TemplateName.IsUnknown() && !data.TemplateName.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"name", data.TemplateName.ValueString())
	}
	if (!data.RemoteAsn.IsUnknown() && !data.RemoteAsn.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"asn", data.RemoteAsn.ValueString())
	}
	if (!data.Description.IsUnknown() && !data.Description.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"desc", data.Description.ValueString())
	}
	if (!data.PeerType.IsUnknown() && !data.PeerType.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"peerType", data.PeerType.ValueString())
	}
	if (!data.SourceInterface.IsUnknown() && !data.SourceInterface.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"srcIf", data.SourceInterface.ValueString())
	}

	return nxos.Body{body}
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody
func (data *BGPPeerTemplate) fromBody(res gjson.Result) {
	data.TemplateName = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	data.RemoteAsn = types.StringValue(res.Get(data.getClassName() + ".attributes.asn").String())
	data.Description = types.StringValue(res.Get(data.getClassName() + ".attributes.desc").String())
	data.PeerType = types.StringValue(res.Get(data.getClassName() + ".attributes.peerType").String())
	data.SourceInterface = types.StringValue(res.Get(data.getClassName() + ".attributes.srcIf").String())
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *BGPPeerTemplate) updateFromBody(res gjson.Result) {
	if !data.TemplateName.IsNull() {
		data.TemplateName = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	} else {
		data.TemplateName = types.StringNull()
	}
	if !data.RemoteAsn.IsNull() {
		data.RemoteAsn = types.StringValue(res.Get(data.getClassName() + ".attributes.asn").String())
	} else {
		data.RemoteAsn = types.StringNull()
	}
	if !data.Description.IsNull() {
		data.Description = types.StringValue(res.Get(data.getClassName() + ".attributes.desc").String())
	} else {
		data.Description = types.StringNull()
	}
	if !data.PeerType.IsNull() {
		data.PeerType = types.StringValue(res.Get(data.getClassName() + ".attributes.peerType").String())
	} else {
		data.PeerType = types.StringNull()
	}
	if !data.SourceInterface.IsNull() {
		data.SourceInterface = types.StringValue(res.Get(data.getClassName() + ".attributes.srcIf").String())
	} else {
		data.SourceInterface = types.StringNull()
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin toDeleteBody
func (data BGPPeerTemplate) toDeleteBody() nxos.Body {
	body := ""

	return nxos.Body{body}
}

// End of section. //template:end toDeleteBody

// Section below is generated&owned by "gen/generator.go". //template:begin getDeleteDns
func (data BGPPeerTemplate) getDeleteDns() []string {
	dns := []string{}
	dns = append(dns, data.getDn())

	return dns
}

// End of section. //template:end getDeleteDns

// Section below is generated&owned by "gen/generator.go". //template:begin getDeletedItems

// End of section. //template:end getDeletedItems
