// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types

type SVIInterfaces struct {
	Device types.String         `tfsdk:"device"`
	Dn     types.String         `tfsdk:"id"`
	Items  []SVIInterfacesItems `tfsdk:"items"`
}

type SVIInterfacesItems struct {
	InterfaceId types.String `tfsdk:"interface_id"`
	AdminState  types.String `tfsdk:"admin_state"`
	Bandwidth   types.Int64  `tfsdk:"bandwidth"`
	Delay       types.Int64  `tfsdk:"delay"`
	Description types.String `tfsdk:"description"`
	Medium      types.String `tfsdk:"medium"`
	Mtu         types.Int64  `tfsdk:"mtu"`
	VrfDn       types.String `tfsdk:"vrf_dn"`
}

type SVIInterfacesIdentity struct {
	Device types.String `tfsdk:"device"`
}

func (data *SVIInterfacesIdentity) toIdentity(ctx context.Context, plan *SVIInterfaces) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
}

func (data *SVIInterfaces) fromIdentity(ctx context.Context, identity *SVIInterfacesIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data SVIInterfaces) getDn() string {
	return "sys/intf"
}

func (data SVIInterfaces) getClassName() string {
	return "interfaceEntity"
}

func (data SVIInterfaces) getItemClassName() string {
	return "sviIf"
}

func (data SVIInterfaces) getItemDn(item SVIInterfacesItems) string {
	return fmt.Sprintf("sys/intf/svi-[%s]", item.InterfaceId.ValueString())
}

func (data SVIInterfaces) getItemRn(item SVIInterfacesItems) string {
	return fmt.Sprintf("svi-[%s]", item.InterfaceId.ValueString())
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data SVIInterfaces) toBody() nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	childrenPath := data.getClassName() + ".children"

	for _, item := range data.Items {
		itemBody := ""
		itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes", map[string]interface{}{})
		if (!item.InterfaceId.IsUnknown() && !item.InterfaceId.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"id", item.InterfaceId.ValueString())
		}
		if (!item.AdminState.IsUnknown() && !item.AdminState.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"adminSt", item.AdminState.ValueString())
		}
		if (!item.Bandwidth.IsUnknown() && !item.Bandwidth.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"bw", strconv.FormatInt(item.Bandwidth.ValueInt64(), 10))
		}
		if (!item.Delay.IsUnknown() && !item.Delay.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"delay", strconv.FormatInt(item.Delay.ValueInt64(), 10))
		}
		if (!item.Description.IsUnknown() && !item.Description.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"descr", item.Description.ValueString())
		}
		if (!item.Medium.IsUnknown() && !item.Medium.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"medium", item.Medium.ValueString())
		}
		if (!item.Mtu.IsUnknown() && !item.Mtu.IsNull()) || false {
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes."+"mtu", strconv.FormatInt(item.Mtu.ValueInt64(), 10))
		}
		var attrs string
		itemChildrenPath := data.getItemClassName() + ".children"
		attrs = "{}"
		if (!item.VrfDn.IsUnknown() && !item.VrfDn.IsNull()) || false {
			attrs, _ = sjson.Set(attrs, "tDn", item.VrfDn.ValueString())
		}
		if attrs != "{}" || false {
			itemBody, _ = sjson.SetRaw(itemBody, itemChildrenPath+".-1.nwRtVrfMbr.attributes", attrs)
		}
		_ = attrs

		body, _ = sjson.SetRaw(body, childrenPath+".-1", itemBody)
	}

	return nxos.Body{body}
}

func (data SVIInterfaces) toDeleteBody(items []SVIInterfacesItems) nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	childrenPath := data.getClassName() + ".children"
	for _, item := range items {
		itemBody := ""
		itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes.rn", data.getItemRn(item))
		itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes.status", "deleted")
		body, _ = sjson.SetRaw(body, childrenPath+".-1", itemBody)
	}
	return nxos.Body{body}
}

func (data SVIInterfaces) toBodyWithDeletes(ctx context.Context, state SVIInterfaces) nxos.Body {
	body := data.toBody()
	childrenPath := data.getClassName() + ".children"
	for _, stateItem := range state.Items {
		found := false
		for _, planItem := range data.Items {
			if planItem.InterfaceId.ValueString() != stateItem.InterfaceId.ValueString() {
				continue
			}
			found = true
			break
		}
		if !found {
			itemBody := ""
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes.rn", data.getItemRn(stateItem))
			itemBody, _ = sjson.Set(itemBody, data.getItemClassName()+".attributes.status", "deleted")
			body.Str, _ = sjson.SetRaw(body.Str, childrenPath+".-1", itemBody)
		}
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *SVIInterfaces) fromBody(res gjson.Result) {
	data.Items = make([]SVIInterfacesItems, 0)
	res.Get(data.getClassName() + ".children").ForEach(func(_, v gjson.Result) bool {
		v.ForEach(func(classname, value gjson.Result) bool {
			if classname.String() == data.getItemClassName() {
				item := SVIInterfacesItems{}
				item.InterfaceId = types.StringValue(value.Get("attributes.id").String())
				item.AdminState = types.StringValue(value.Get("attributes.adminSt").String())
				item.Bandwidth = types.Int64Value(value.Get("attributes.bw").Int())
				item.Delay = types.Int64Value(value.Get("attributes.delay").Int())
				item.Description = types.StringValue(value.Get("attributes.descr").String())
				item.Medium = types.StringValue(value.Get("attributes.medium").String())
				item.Mtu = types.Int64Value(value.Get("attributes.mtu").Int())
				{
					var rnwRtVrfMbr gjson.Result
					value.Get("children").ForEach(
						func(_, nestedV gjson.Result) bool {
							key := nestedV.Get("nwRtVrfMbr.attributes.rn").String()
							if key == "rtvrfMbr" {
								rnwRtVrfMbr = nestedV
								return false
							}
							return true
						},
					)
					item.VrfDn = types.StringValue(rnwRtVrfMbr.Get("nwRtVrfMbr.attributes.tDn").String())
				}
				data.Items = append(data.Items, item)
			}
			return true
		})
		return true
	})
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *SVIInterfaces) updateFromBody(res gjson.Result) {
	for i := range data.Items {
		// Find the matching item in the response by id attributes
		res.Get(data.getClassName() + ".children").ForEach(func(_, v gjson.Result) bool {
			v.ForEach(func(classname, value gjson.Result) bool {
				if classname.String() == data.getItemClassName() {
					if value.Get("attributes.id").String() != data.Items[i].InterfaceId.ValueString() {
						return true
					}
					// Found matching item, update attributes
					if !data.Items[i].InterfaceId.IsNull() {
						data.Items[i].InterfaceId = types.StringValue(value.Get("attributes.id").String())
					} else {
						data.Items[i].InterfaceId = types.StringNull()
					}
					if !data.Items[i].AdminState.IsNull() {
						data.Items[i].AdminState = types.StringValue(value.Get("attributes.adminSt").String())
					} else {
						data.Items[i].AdminState = types.StringNull()
					}
					if !data.Items[i].Bandwidth.IsNull() {
						data.Items[i].Bandwidth = types.Int64Value(value.Get("attributes.bw").Int())
					} else {
						data.Items[i].Bandwidth = types.Int64Null()
					}
					if !data.Items[i].Delay.IsNull() {
						data.Items[i].Delay = types.Int64Value(value.Get("attributes.delay").Int())
					} else {
						data.Items[i].Delay = types.Int64Null()
					}
					if !data.Items[i].Description.IsNull() {
						data.Items[i].Description = types.StringValue(value.Get("attributes.descr").String())
					} else {
						data.Items[i].Description = types.StringNull()
					}
					if !data.Items[i].Medium.IsNull() {
						data.Items[i].Medium = types.StringValue(value.Get("attributes.medium").String())
					} else {
						data.Items[i].Medium = types.StringNull()
					}
					if !data.Items[i].Mtu.IsNull() {
						data.Items[i].Mtu = types.Int64Value(value.Get("attributes.mtu").Int())
					} else {
						data.Items[i].Mtu = types.Int64Null()
					}
					{
						var rnwRtVrfMbr gjson.Result
						value.Get("children").ForEach(
							func(_, nestedV gjson.Result) bool {
								key := nestedV.Get("nwRtVrfMbr.attributes.rn").String()
								if key == "rtvrfMbr" {
									rnwRtVrfMbr = nestedV
									return false
								}
								return true
							},
						)
						if !data.Items[i].VrfDn.IsNull() {
							data.Items[i].VrfDn = types.StringValue(rnwRtVrfMbr.Get("nwRtVrfMbr.attributes.tDn").String())
						} else {
							data.Items[i].VrfDn = types.StringNull()
						}
					}
				}
				return true
			})
			return true
		})
	}
}

// End of section. //template:end updateFromBody
