// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type DefaultQOSClassMap struct {
	Device    types.String `tfsdk:"device"`
	Dn        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	MatchType types.String `tfsdk:"match_type"`
}

type DefaultQOSClassMapIdentity struct {
	Device types.String `tfsdk:"device"`
	Name   types.String `tfsdk:"name"`
}

func (data *DefaultQOSClassMapIdentity) toIdentity(ctx context.Context, plan *DefaultQOSClassMap) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
	data.Name = plan.Name
}

func (data *DefaultQOSClassMap) fromIdentity(ctx context.Context, identity *DefaultQOSClassMapIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
	data.Name = identity.Name
}

func (data DefaultQOSClassMap) getDn() string {
	return fmt.Sprintf("sys/ipqos/dflt/c/name-[%s]", data.Name.ValueString())
}

func (data DefaultQOSClassMap) getClassName() string {
	return "ipqosCMapInst"
}

func (data DefaultQOSClassMap) toBody(statusReplace bool) nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	if statusReplace {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"status", "replaced")
	}
	if (!data.Name.IsUnknown() && !data.Name.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"name", data.Name.ValueString())
	}
	if (!data.MatchType.IsUnknown() && !data.MatchType.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"matchType", data.MatchType.ValueString())
	}

	return nxos.Body{body}
}

func (data *DefaultQOSClassMap) fromBody(res gjson.Result) {
	data.Name = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	data.MatchType = types.StringValue(res.Get(data.getClassName() + ".attributes.matchType").String())
}

func (data *DefaultQOSClassMap) updateFromBody(res gjson.Result) {
	if !data.Name.IsNull() {
		data.Name = types.StringValue(res.Get(data.getClassName() + ".attributes.name").String())
	} else {
		data.Name = types.StringNull()
	}
	if !data.MatchType.IsNull() {
		data.MatchType = types.StringValue(res.Get(data.getClassName() + ".attributes.matchType").String())
	} else {
		data.MatchType = types.StringNull()
	}
}

func (data DefaultQOSClassMap) toDeleteBody() nxos.Body {
	body := ""

	return nxos.Body{body}
}
