// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
)

type DefaultQOSPolicyInterfaceInPolicyMap struct {
	Dn           types.String `tfsdk:"id"`
	Interface_id types.String `tfsdk:"interface_id"`
	Name         types.String `tfsdk:"policy_map_name"`
}

func (data DefaultQOSPolicyInterfaceInPolicyMap) getDn() string {
	return fmt.Sprintf("sys/ipqos/dflt/policy/in/intf-[%s]/pmap", data.Interface_id.Value)
}

func (data DefaultQOSPolicyInterfaceInPolicyMap) getClassName() string {
	return "ipqosInst"
}

func (data DefaultQOSPolicyInterfaceInPolicyMap) toBody() nxos.Body {
	attrs := nxos.Body{}.
		Set("name", data.Name.Value)
	return nxos.Body{}.SetRaw(data.getClassName()+".attributes", attrs.Str)
}

func (data *DefaultQOSPolicyInterfaceInPolicyMap) fromBody(res gjson.Result) {
	data.Dn.Value = res.Get("*.attributes.dn").String()
	data.Name.Value = res.Get("*.attributes.name").String()
}

func (data *DefaultQOSPolicyInterfaceInPolicyMap) fromPlan(plan DefaultQOSPolicyInterfaceInPolicyMap) {
	data.Interface_id.Value = plan.Interface_id.Value
}
