// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type BannerPrelogin struct {
	Device     types.String `tfsdk:"device"`
	Dn         types.String `tfsdk:"id"`
	MotdBanner types.String `tfsdk:"motd_banner"`
}

func (data BannerPrelogin) getDn() string {
	return "sys/userext/preloginbanner"
}

func (data BannerPrelogin) getClassName() string {
	return "aaaPreLoginBanner"
}

func (data BannerPrelogin) toBody(statusReplace bool) nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	if statusReplace {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"status", "replaced")
	}
	if (!data.MotdBanner.IsUnknown() && !data.MotdBanner.IsNull()) || true {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"message", data.MotdBanner.ValueString())
	}

	return nxos.Body{body}
}

func (data *BannerPrelogin) fromBody(res gjson.Result, all bool) {
	if !data.MotdBanner.IsNull() || all {
		data.MotdBanner = types.StringValue(res.Get(data.getClassName() + ".attributes.message").String())
	} else {
		data.MotdBanner = types.StringNull()
	}
}

func (data BannerPrelogin) toDeleteBody() nxos.Body {
	body := ""

	return nxos.Body{body}
}
