// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-nxos/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/go-nxos"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types

type HSRP struct {
	Device                            types.String              `tfsdk:"device"`
	Dn                                types.String              `tfsdk:"id"`
	AdminState                        types.String              `tfsdk:"admin_state"`
	InstanceAdminState                types.String              `tfsdk:"instance_admin_state"`
	Bfd                               types.String              `tfsdk:"bfd"`
	Control                           types.String              `tfsdk:"control"`
	ExtendedHoldInterval              types.Int64               `tfsdk:"extended_hold_interval"`
	ExtendedHoldIntervalConfiguration types.String              `tfsdk:"extended_hold_interval_configuration"`
	Interfaces                        map[string]HSRPInterfaces `tfsdk:"interfaces"`
}

type HSRPInterfaces struct {
	AdminState                      types.String                    `tfsdk:"admin_state"`
	Bfd                             types.String                    `tfsdk:"bfd"`
	BiaScope                        types.String                    `tfsdk:"bia_scope"`
	Control                         types.String                    `tfsdk:"control"`
	DelayMinimum                    types.Int64                     `tfsdk:"delay_minimum"`
	Description                     types.String                    `tfsdk:"description"`
	MacRefreshInterval              types.Int64                     `tfsdk:"mac_refresh_interval"`
	MacRefreshIntervalConfiguration types.String                    `tfsdk:"mac_refresh_interval_configuration"`
	Name                            types.String                    `tfsdk:"name"`
	ReloadDelay                     types.Int64                     `tfsdk:"reload_delay"`
	Version                         types.String                    `tfsdk:"version"`
	Groups                          map[string]HSRPInterfacesGroups `tfsdk:"groups"`
}

type HSRPInterfacesGroups struct {
	AuthenticationMd5CompatibilityMode types.String `tfsdk:"authentication_md5_compatibility_mode"`
	AuthenticationMd5KeyChainName      types.String `tfsdk:"authentication_md5_key_chain_name"`
	AuthenticationMd5KeyName           types.String `tfsdk:"authentication_md5_key_name"`
	AuthenticationMd5KeyStringType     types.String `tfsdk:"authentication_md5_key_string_type"`
	AuthenticationMd5Timeout           types.Int64  `tfsdk:"authentication_md5_timeout"`
	AuthenticationMd5Type              types.String `tfsdk:"authentication_md5_type"`
	AuthenticationSecret               types.String `tfsdk:"authentication_secret"`
	AuthenticationSecretWo             types.String `tfsdk:"authentication_secret_wo"`
	AuthenticationSecretWoVersion      types.Int64  `tfsdk:"authentication_secret_wo_version"`
	AuthenticationType                 types.String `tfsdk:"authentication_type"`
	Control                            types.String `tfsdk:"control"`
	Follow                             types.String `tfsdk:"follow"`
	ForwardingLowerThreshold           types.Int64  `tfsdk:"forwarding_lower_threshold"`
	HelloInterval                      types.Int64  `tfsdk:"hello_interval"`
	HoldInterval                       types.Int64  `tfsdk:"hold_interval"`
	IpAddress                          types.String `tfsdk:"ip_address"`
	IpObtainMode                       types.String `tfsdk:"ip_obtain_mode"`
	MacAddress                         types.String `tfsdk:"mac_address"`
	Name                               types.String `tfsdk:"name"`
	PreemptDelayMinimum                types.Int64  `tfsdk:"preempt_delay_minimum"`
	PreemptDelayReload                 types.Int64  `tfsdk:"preempt_delay_reload"`
	PreemptDelaySync                   types.Int64  `tfsdk:"preempt_delay_sync"`
	Priority                           types.Int64  `tfsdk:"priority"`
}

type HSRPIdentity struct {
	Device types.String `tfsdk:"device"`
}

func (data *HSRPIdentity) toIdentity(ctx context.Context, plan *HSRP) {
	if plan.Device.IsNull() {
		data.Device = types.StringValue("")
	} else {
		data.Device = plan.Device
	}
}

func (data *HSRP) fromIdentity(ctx context.Context, identity *HSRPIdentity) {
	if identity.Device.ValueString() == "" {
		data.Device = types.StringNull()
	} else {
		data.Device = identity.Device
	}
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data HSRP) getDn() string {
	return "sys/hsrp"
}

func (data HSRPInterfaces) getRn(key string) string {
	return fmt.Sprintf("if-[%s]", key)
}

func (data HSRPInterfacesGroups) getRn(key string) string {
	keyParts := strings.SplitN(key, ";", 2)
	return fmt.Sprintf("grp-%v-%s", helpers.Must(strconv.ParseInt(keyParts[0], 10, 64)), keyParts[1])
}

func (data HSRP) getClassName() string {
	return "hsrpEntity"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBody

func (data HSRP) toBody(config HSRP) nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes", map[string]interface{}{})
	if !data.AdminState.IsUnknown() && !data.AdminState.IsNull() && !config.AdminState.IsNull() {
		body, _ = sjson.Set(body, data.getClassName()+".attributes."+"adminSt", data.AdminState.ValueString())
	}
	var attrs string
	childrenPath := data.getClassName() + ".children"
	{
		childIndex := len(gjson.Get(body, childrenPath).Array())
		childBodyPath := childrenPath + "." + strconv.Itoa(childIndex) + ".hsrpInst"
		attrs = "{}"
		if !data.InstanceAdminState.IsUnknown() && !data.InstanceAdminState.IsNull() && !config.InstanceAdminState.IsNull() {
			attrs, _ = sjson.Set(attrs, "adminSt", data.InstanceAdminState.ValueString())
		}
		if !data.Bfd.IsUnknown() && !data.Bfd.IsNull() && !config.Bfd.IsNull() {
			attrs, _ = sjson.Set(attrs, "bfd", data.Bfd.ValueString())
		}
		if !data.Control.IsUnknown() && !data.Control.IsNull() && !config.Control.IsNull() {
			attrs, _ = sjson.Set(attrs, "ctrl", data.Control.ValueString())
		}
		if !data.ExtendedHoldInterval.IsUnknown() && !data.ExtendedHoldInterval.IsNull() && !config.ExtendedHoldInterval.IsNull() {
			attrs, _ = sjson.Set(attrs, "extendedHoldIntvl", strconv.FormatInt(data.ExtendedHoldInterval.ValueInt64(), 10))
		}
		if !data.ExtendedHoldIntervalConfiguration.IsUnknown() && !data.ExtendedHoldIntervalConfiguration.IsNull() && !config.ExtendedHoldIntervalConfiguration.IsNull() {
			attrs, _ = sjson.Set(attrs, "extendedHoldIntvlCfg", data.ExtendedHoldIntervalConfiguration.ValueString())
		}
		body, _ = sjson.SetRaw(body, childBodyPath+".attributes", attrs)
		nestedChildrenPath := childBodyPath + ".children"
		for key, child := range data.Interfaces {
			configChild, configChildOk := config.Interfaces[key]
			_ = configChild
			_ = configChildOk
			attrs = "{}"
			attrs, _ = sjson.Set(attrs, "id", key)
			if configChildOk && !child.AdminState.IsUnknown() && !child.AdminState.IsNull() && !configChild.AdminState.IsNull() {
				attrs, _ = sjson.Set(attrs, "adminSt", child.AdminState.ValueString())
			}
			if configChildOk && !child.Bfd.IsUnknown() && !child.Bfd.IsNull() && !configChild.Bfd.IsNull() {
				attrs, _ = sjson.Set(attrs, "bfd", child.Bfd.ValueString())
			}
			if configChildOk && !child.BiaScope.IsUnknown() && !child.BiaScope.IsNull() && !configChild.BiaScope.IsNull() {
				attrs, _ = sjson.Set(attrs, "biaScope", child.BiaScope.ValueString())
			}
			if configChildOk && !child.Control.IsUnknown() && !child.Control.IsNull() && !configChild.Control.IsNull() {
				attrs, _ = sjson.Set(attrs, "ctrl", child.Control.ValueString())
			}
			if configChildOk && !child.DelayMinimum.IsUnknown() && !child.DelayMinimum.IsNull() && !configChild.DelayMinimum.IsNull() {
				attrs, _ = sjson.Set(attrs, "delayIntfMin", strconv.FormatInt(child.DelayMinimum.ValueInt64(), 10))
			}
			if configChildOk && !child.Description.IsUnknown() && !child.Description.IsNull() && !configChild.Description.IsNull() {
				attrs, _ = sjson.Set(attrs, "descr", child.Description.ValueString())
			}
			if configChildOk && !child.MacRefreshInterval.IsUnknown() && !child.MacRefreshInterval.IsNull() && !configChild.MacRefreshInterval.IsNull() {
				attrs, _ = sjson.Set(attrs, "macRefreshIntvl", strconv.FormatInt(child.MacRefreshInterval.ValueInt64(), 10))
			}
			if configChildOk && !child.MacRefreshIntervalConfiguration.IsUnknown() && !child.MacRefreshIntervalConfiguration.IsNull() && !configChild.MacRefreshIntervalConfiguration.IsNull() {
				attrs, _ = sjson.Set(attrs, "macRefreshIntvlCfg", child.MacRefreshIntervalConfiguration.ValueString())
			}
			if configChildOk && !child.Name.IsUnknown() && !child.Name.IsNull() && !configChild.Name.IsNull() {
				attrs, _ = sjson.Set(attrs, "name", child.Name.ValueString())
			}
			if configChildOk && !child.ReloadDelay.IsUnknown() && !child.ReloadDelay.IsNull() && !configChild.ReloadDelay.IsNull() {
				attrs, _ = sjson.Set(attrs, "reloadDelay", strconv.FormatInt(child.ReloadDelay.ValueInt64(), 10))
			}
			if configChildOk && !child.Version.IsUnknown() && !child.Version.IsNull() && !configChild.Version.IsNull() {
				attrs, _ = sjson.Set(attrs, "version", child.Version.ValueString())
			}
			body, _ = sjson.SetRaw(body, nestedChildrenPath+".-1.hsrpIf.attributes", attrs)
			{
				nestedIndex := len(gjson.Get(body, nestedChildrenPath).Array()) - 1
				nestedChildrenPath := nestedChildrenPath + "." + strconv.Itoa(nestedIndex) + ".hsrpIf.children"
				for key, child := range child.Groups {
					configChild, configChildOk := configChild.Groups[key]
					_ = configChild
					_ = configChildOk
					attrs = "{}"
					keyParts := strings.SplitN(key, ";", 2)
					attrs, _ = sjson.Set(attrs, "id", keyParts[0])
					attrs, _ = sjson.Set(attrs, "af", keyParts[1])
					if configChildOk && !child.AuthenticationMd5CompatibilityMode.IsUnknown() && !child.AuthenticationMd5CompatibilityMode.IsNull() && !configChild.AuthenticationMd5CompatibilityMode.IsNull() {
						attrs, _ = sjson.Set(attrs, "authMd5CompatibilityMode", child.AuthenticationMd5CompatibilityMode.ValueString())
					}
					if configChildOk && !child.AuthenticationMd5KeyChainName.IsUnknown() && !child.AuthenticationMd5KeyChainName.IsNull() && !configChild.AuthenticationMd5KeyChainName.IsNull() {
						attrs, _ = sjson.Set(attrs, "authMd5KeyChainName", child.AuthenticationMd5KeyChainName.ValueString())
					}
					if configChildOk && !child.AuthenticationMd5KeyName.IsUnknown() && !child.AuthenticationMd5KeyName.IsNull() && !configChild.AuthenticationMd5KeyName.IsNull() {
						attrs, _ = sjson.Set(attrs, "authMd5KeyName", child.AuthenticationMd5KeyName.ValueString())
					}
					if configChildOk && !child.AuthenticationMd5KeyStringType.IsUnknown() && !child.AuthenticationMd5KeyStringType.IsNull() && !configChild.AuthenticationMd5KeyStringType.IsNull() {
						attrs, _ = sjson.Set(attrs, "authMd5KeyStringType", child.AuthenticationMd5KeyStringType.ValueString())
					}
					if configChildOk && !child.AuthenticationMd5Timeout.IsUnknown() && !child.AuthenticationMd5Timeout.IsNull() && !configChild.AuthenticationMd5Timeout.IsNull() {
						attrs, _ = sjson.Set(attrs, "authMd5Timeout", strconv.FormatInt(child.AuthenticationMd5Timeout.ValueInt64(), 10))
					}
					if configChildOk && !child.AuthenticationMd5Type.IsUnknown() && !child.AuthenticationMd5Type.IsNull() && !configChild.AuthenticationMd5Type.IsNull() {
						attrs, _ = sjson.Set(attrs, "authMd5Type", child.AuthenticationMd5Type.ValueString())
					}
					if configChildOk && !configChild.AuthenticationSecretWo.IsNull() {
						attrs, _ = sjson.Set(attrs, "authSecret", configChild.AuthenticationSecretWo.ValueString())
					} else if !child.AuthenticationSecret.IsUnknown() && !child.AuthenticationSecret.IsNull() {
						attrs, _ = sjson.Set(attrs, "authSecret", child.AuthenticationSecret.ValueString())
					}
					if configChildOk && !child.AuthenticationType.IsUnknown() && !child.AuthenticationType.IsNull() && !configChild.AuthenticationType.IsNull() {
						attrs, _ = sjson.Set(attrs, "authType", child.AuthenticationType.ValueString())
					}
					if configChildOk && !child.Control.IsUnknown() && !child.Control.IsNull() && !configChild.Control.IsNull() {
						attrs, _ = sjson.Set(attrs, "ctrl", child.Control.ValueString())
					}
					if configChildOk && !child.Follow.IsUnknown() && !child.Follow.IsNull() && !configChild.Follow.IsNull() {
						attrs, _ = sjson.Set(attrs, "follow", child.Follow.ValueString())
					}
					if configChildOk && !child.ForwardingLowerThreshold.IsUnknown() && !child.ForwardingLowerThreshold.IsNull() && !configChild.ForwardingLowerThreshold.IsNull() {
						attrs, _ = sjson.Set(attrs, "fwdLwrThrld", strconv.FormatInt(child.ForwardingLowerThreshold.ValueInt64(), 10))
					}
					if configChildOk && !child.HelloInterval.IsUnknown() && !child.HelloInterval.IsNull() && !configChild.HelloInterval.IsNull() {
						attrs, _ = sjson.Set(attrs, "helloIntvl", strconv.FormatInt(child.HelloInterval.ValueInt64(), 10))
					}
					if configChildOk && !child.HoldInterval.IsUnknown() && !child.HoldInterval.IsNull() && !configChild.HoldInterval.IsNull() {
						attrs, _ = sjson.Set(attrs, "holdIntvl", strconv.FormatInt(child.HoldInterval.ValueInt64(), 10))
					}
					if configChildOk && !child.IpAddress.IsUnknown() && !child.IpAddress.IsNull() && !configChild.IpAddress.IsNull() {
						attrs, _ = sjson.Set(attrs, "ip", child.IpAddress.ValueString())
					}
					if configChildOk && !child.IpObtainMode.IsUnknown() && !child.IpObtainMode.IsNull() && !configChild.IpObtainMode.IsNull() {
						attrs, _ = sjson.Set(attrs, "ipObtainMode", child.IpObtainMode.ValueString())
					}
					if configChildOk && !child.MacAddress.IsUnknown() && !child.MacAddress.IsNull() && !configChild.MacAddress.IsNull() {
						attrs, _ = sjson.Set(attrs, "mac", child.MacAddress.ValueString())
					}
					if configChildOk && !child.Name.IsUnknown() && !child.Name.IsNull() && !configChild.Name.IsNull() {
						attrs, _ = sjson.Set(attrs, "name", child.Name.ValueString())
					}
					if configChildOk && !child.PreemptDelayMinimum.IsUnknown() && !child.PreemptDelayMinimum.IsNull() && !configChild.PreemptDelayMinimum.IsNull() {
						attrs, _ = sjson.Set(attrs, "preemptDelayMin", strconv.FormatInt(child.PreemptDelayMinimum.ValueInt64(), 10))
					}
					if configChildOk && !child.PreemptDelayReload.IsUnknown() && !child.PreemptDelayReload.IsNull() && !configChild.PreemptDelayReload.IsNull() {
						attrs, _ = sjson.Set(attrs, "preemptDelayReload", strconv.FormatInt(child.PreemptDelayReload.ValueInt64(), 10))
					}
					if configChildOk && !child.PreemptDelaySync.IsUnknown() && !child.PreemptDelaySync.IsNull() && !configChild.PreemptDelaySync.IsNull() {
						attrs, _ = sjson.Set(attrs, "preemptDelaySync", strconv.FormatInt(child.PreemptDelaySync.ValueInt64(), 10))
					}
					if configChildOk && !child.Priority.IsUnknown() && !child.Priority.IsNull() && !configChild.Priority.IsNull() {
						attrs, _ = sjson.Set(attrs, "prio", strconv.FormatInt(child.Priority.ValueInt64(), 10))
					}
					body, _ = sjson.SetRaw(body, nestedChildrenPath+".-1.hsrpGroup.attributes", attrs)
				}
			}
		}
	}

	return nxos.Body{Str: body}
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody

func (data *HSRP) fromBody(res gjson.Result) {
	data.AdminState = types.StringValue(res.Get(data.getClassName() + ".attributes.adminSt").String())
	{
		var rhsrpInst gjson.Result
		res.Get(data.getClassName() + ".children").ForEach(
			func(_, v gjson.Result) bool {
				rnValue := v.Get("hsrpInst.attributes.rn").String()
				if rnValue == "inst" {
					rhsrpInst = v
					return false
				}
				return true
			},
		)
		data.InstanceAdminState = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.adminSt").String())
		data.Bfd = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.bfd").String())
		data.Control = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.ctrl").String())
		data.ExtendedHoldInterval = types.Int64Value(rhsrpInst.Get("hsrpInst.attributes.extendedHoldIntvl").Int())
		data.ExtendedHoldIntervalConfiguration = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.extendedHoldIntvlCfg").String())
		rhsrpInst.Get("hsrpInst.children").ForEach(
			func(_, v gjson.Result) bool {
				v.ForEach(
					func(classname, value gjson.Result) bool {
						if classname.String() == "hsrpIf" {
							var child HSRPInterfaces
							child.AdminState = types.StringValue(value.Get("attributes.adminSt").String())
							child.Bfd = types.StringValue(value.Get("attributes.bfd").String())
							child.BiaScope = types.StringValue(value.Get("attributes.biaScope").String())
							child.Control = types.StringValue(value.Get("attributes.ctrl").String())
							child.DelayMinimum = types.Int64Value(value.Get("attributes.delayIntfMin").Int())
							child.Description = types.StringValue(value.Get("attributes.descr").String())
							child.MacRefreshInterval = types.Int64Value(value.Get("attributes.macRefreshIntvl").Int())
							child.MacRefreshIntervalConfiguration = types.StringValue(value.Get("attributes.macRefreshIntvlCfg").String())
							child.Name = types.StringValue(value.Get("attributes.name").String())
							child.ReloadDelay = types.Int64Value(value.Get("attributes.reloadDelay").Int())
							child.Version = types.StringValue(value.Get("attributes.version").String())
							mapKey := value.Get("attributes.id").String()
							value.Get("children").ForEach(
								func(_, nestedV gjson.Result) bool {
									nestedV.ForEach(
										func(nestedClassname, nestedValue gjson.Result) bool {
											if nestedClassname.String() == "hsrpGroup" {
												var nestedChildhsrpGroup HSRPInterfacesGroups
												nestedChildhsrpGroup.AuthenticationMd5CompatibilityMode = types.StringValue(nestedValue.Get("attributes.authMd5CompatibilityMode").String())
												nestedChildhsrpGroup.AuthenticationMd5KeyChainName = types.StringValue(nestedValue.Get("attributes.authMd5KeyChainName").String())
												nestedChildhsrpGroup.AuthenticationMd5KeyName = types.StringValue(nestedValue.Get("attributes.authMd5KeyName").String())
												nestedChildhsrpGroup.AuthenticationMd5KeyStringType = types.StringValue(nestedValue.Get("attributes.authMd5KeyStringType").String())
												nestedChildhsrpGroup.AuthenticationMd5Timeout = types.Int64Value(nestedValue.Get("attributes.authMd5Timeout").Int())
												nestedChildhsrpGroup.AuthenticationMd5Type = types.StringValue(nestedValue.Get("attributes.authMd5Type").String())
												nestedChildhsrpGroup.AuthenticationType = types.StringValue(nestedValue.Get("attributes.authType").String())
												nestedChildhsrpGroup.Control = types.StringValue(nestedValue.Get("attributes.ctrl").String())
												nestedChildhsrpGroup.Follow = types.StringValue(nestedValue.Get("attributes.follow").String())
												nestedChildhsrpGroup.ForwardingLowerThreshold = types.Int64Value(nestedValue.Get("attributes.fwdLwrThrld").Int())
												nestedChildhsrpGroup.HelloInterval = types.Int64Value(nestedValue.Get("attributes.helloIntvl").Int())
												nestedChildhsrpGroup.HoldInterval = types.Int64Value(nestedValue.Get("attributes.holdIntvl").Int())
												nestedChildhsrpGroup.IpAddress = types.StringValue(nestedValue.Get("attributes.ip").String())
												nestedChildhsrpGroup.IpObtainMode = types.StringValue(nestedValue.Get("attributes.ipObtainMode").String())
												nestedChildhsrpGroup.MacAddress = types.StringValue(nestedValue.Get("attributes.mac").String())
												nestedChildhsrpGroup.Name = types.StringValue(nestedValue.Get("attributes.name").String())
												nestedChildhsrpGroup.PreemptDelayMinimum = types.Int64Value(nestedValue.Get("attributes.preemptDelayMin").Int())
												nestedChildhsrpGroup.PreemptDelayReload = types.Int64Value(nestedValue.Get("attributes.preemptDelayReload").Int())
												nestedChildhsrpGroup.PreemptDelaySync = types.Int64Value(nestedValue.Get("attributes.preemptDelaySync").Int())
												nestedChildhsrpGroup.Priority = types.Int64Value(nestedValue.Get("attributes.prio").Int())
												nestedMapKey := nestedValue.Get("attributes.id").String() + ";" + nestedValue.Get("attributes.af").String()
												if child.Groups == nil {
													child.Groups = make(map[string]HSRPInterfacesGroups)
												}
												child.Groups[nestedMapKey] = nestedChildhsrpGroup
											}
											return true
										},
									)
									return true
								},
							)
							if data.Interfaces == nil {
								data.Interfaces = make(map[string]HSRPInterfaces)
							}
							data.Interfaces[mapKey] = child
						}
						return true
					},
				)
				return true
			},
		)
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody

func (data *HSRP) updateFromBody(res gjson.Result) {
	if !data.AdminState.IsNull() {
		data.AdminState = types.StringValue(res.Get(data.getClassName() + ".attributes.adminSt").String())
	} else {
		data.AdminState = types.StringNull()
	}
	var rhsrpInst gjson.Result
	res.Get(data.getClassName() + ".children").ForEach(
		func(_, v gjson.Result) bool {
			rnValue := v.Get("hsrpInst.attributes.rn").String()
			if rnValue == "inst" {
				rhsrpInst = v
				return false
			}
			return true
		},
	)
	if !data.InstanceAdminState.IsNull() {
		data.InstanceAdminState = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.adminSt").String())
	} else {
		data.InstanceAdminState = types.StringNull()
	}
	if !data.Bfd.IsNull() {
		data.Bfd = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.bfd").String())
	} else {
		data.Bfd = types.StringNull()
	}
	if !data.Control.IsNull() {
		data.Control = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.ctrl").String())
	} else {
		data.Control = types.StringNull()
	}
	if !data.ExtendedHoldInterval.IsNull() {
		data.ExtendedHoldInterval = types.Int64Value(rhsrpInst.Get("hsrpInst.attributes.extendedHoldIntvl").Int())
	} else {
		data.ExtendedHoldInterval = types.Int64Null()
	}
	if !data.ExtendedHoldIntervalConfiguration.IsNull() {
		data.ExtendedHoldIntervalConfiguration = types.StringValue(rhsrpInst.Get("hsrpInst.attributes.extendedHoldIntvlCfg").String())
	} else {
		data.ExtendedHoldIntervalConfiguration = types.StringNull()
	}
	for key, item := range data.Interfaces {
		var rhsrpIf gjson.Result
		rhsrpInst.Get("hsrpInst.children").ForEach(
			func(_, v gjson.Result) bool {
				if v.Get("hsrpIf.attributes.id").String() == key {
					rhsrpIf = v
					return false
				}
				return true
			},
		)
		if !rhsrpIf.Exists() {
			delete(data.Interfaces, key)
			continue
		}
		if !item.AdminState.IsNull() {
			item.AdminState = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.adminSt").String())
		} else {
			item.AdminState = types.StringNull()
		}
		if !item.Bfd.IsNull() {
			item.Bfd = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.bfd").String())
		} else {
			item.Bfd = types.StringNull()
		}
		if !item.BiaScope.IsNull() {
			item.BiaScope = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.biaScope").String())
		} else {
			item.BiaScope = types.StringNull()
		}
		if !item.Control.IsNull() {
			item.Control = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.ctrl").String())
		} else {
			item.Control = types.StringNull()
		}
		if !item.DelayMinimum.IsNull() {
			item.DelayMinimum = types.Int64Value(rhsrpIf.Get("hsrpIf.attributes.delayIntfMin").Int())
		} else {
			item.DelayMinimum = types.Int64Null()
		}
		if !item.Description.IsNull() {
			item.Description = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.descr").String())
		} else {
			item.Description = types.StringNull()
		}
		if !item.MacRefreshInterval.IsNull() {
			item.MacRefreshInterval = types.Int64Value(rhsrpIf.Get("hsrpIf.attributes.macRefreshIntvl").Int())
		} else {
			item.MacRefreshInterval = types.Int64Null()
		}
		if !item.MacRefreshIntervalConfiguration.IsNull() {
			item.MacRefreshIntervalConfiguration = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.macRefreshIntvlCfg").String())
		} else {
			item.MacRefreshIntervalConfiguration = types.StringNull()
		}
		if !item.Name.IsNull() {
			item.Name = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.name").String())
		} else {
			item.Name = types.StringNull()
		}
		if !item.ReloadDelay.IsNull() {
			item.ReloadDelay = types.Int64Value(rhsrpIf.Get("hsrpIf.attributes.reloadDelay").Int())
		} else {
			item.ReloadDelay = types.Int64Null()
		}
		if !item.Version.IsNull() {
			item.Version = types.StringValue(rhsrpIf.Get("hsrpIf.attributes.version").String())
		} else {
			item.Version = types.StringNull()
		}
		for nc := range item.Groups {
			ncItem := item.Groups[nc]
			keyParts := strings.SplitN(nc, ";", 2)
			var rhsrpGroup gjson.Result
			rhsrpIf.Get("hsrpIf.children").ForEach(
				func(_, v gjson.Result) bool {
					if v.Get("hsrpGroup.attributes.id").String() == keyParts[0] &&
						v.Get("hsrpGroup.attributes.af").String() == keyParts[1] {
						rhsrpGroup = v
						return false
					}
					return true
				},
			)
			if !rhsrpGroup.Exists() {
				delete(item.Groups, nc)
				continue
			}
			if !ncItem.AuthenticationMd5CompatibilityMode.IsNull() {
				ncItem.AuthenticationMd5CompatibilityMode = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.authMd5CompatibilityMode").String())
			} else {
				ncItem.AuthenticationMd5CompatibilityMode = types.StringNull()
			}
			if !ncItem.AuthenticationMd5KeyChainName.IsNull() {
				ncItem.AuthenticationMd5KeyChainName = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.authMd5KeyChainName").String())
			} else {
				ncItem.AuthenticationMd5KeyChainName = types.StringNull()
			}
			if !ncItem.AuthenticationMd5KeyName.IsNull() {
				ncItem.AuthenticationMd5KeyName = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.authMd5KeyName").String())
			} else {
				ncItem.AuthenticationMd5KeyName = types.StringNull()
			}
			if !ncItem.AuthenticationMd5KeyStringType.IsNull() {
				ncItem.AuthenticationMd5KeyStringType = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.authMd5KeyStringType").String())
			} else {
				ncItem.AuthenticationMd5KeyStringType = types.StringNull()
			}
			if !ncItem.AuthenticationMd5Timeout.IsNull() {
				ncItem.AuthenticationMd5Timeout = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.authMd5Timeout").Int())
			} else {
				ncItem.AuthenticationMd5Timeout = types.Int64Null()
			}
			if !ncItem.AuthenticationMd5Type.IsNull() {
				ncItem.AuthenticationMd5Type = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.authMd5Type").String())
			} else {
				ncItem.AuthenticationMd5Type = types.StringNull()
			}
			if !ncItem.AuthenticationType.IsNull() {
				ncItem.AuthenticationType = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.authType").String())
			} else {
				ncItem.AuthenticationType = types.StringNull()
			}
			if !ncItem.Control.IsNull() {
				ncItem.Control = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.ctrl").String())
			} else {
				ncItem.Control = types.StringNull()
			}
			if !ncItem.Follow.IsNull() {
				ncItem.Follow = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.follow").String())
			} else {
				ncItem.Follow = types.StringNull()
			}
			if !ncItem.ForwardingLowerThreshold.IsNull() {
				ncItem.ForwardingLowerThreshold = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.fwdLwrThrld").Int())
			} else {
				ncItem.ForwardingLowerThreshold = types.Int64Null()
			}
			if !ncItem.HelloInterval.IsNull() {
				ncItem.HelloInterval = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.helloIntvl").Int())
			} else {
				ncItem.HelloInterval = types.Int64Null()
			}
			if !ncItem.HoldInterval.IsNull() {
				ncItem.HoldInterval = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.holdIntvl").Int())
			} else {
				ncItem.HoldInterval = types.Int64Null()
			}
			if !ncItem.IpAddress.IsNull() {
				ncItem.IpAddress = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.ip").String())
			} else {
				ncItem.IpAddress = types.StringNull()
			}
			if !ncItem.IpObtainMode.IsNull() {
				ncItem.IpObtainMode = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.ipObtainMode").String())
			} else {
				ncItem.IpObtainMode = types.StringNull()
			}
			if !ncItem.MacAddress.IsNull() {
				ncItem.MacAddress = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.mac").String())
			} else {
				ncItem.MacAddress = types.StringNull()
			}
			if !ncItem.Name.IsNull() {
				ncItem.Name = types.StringValue(rhsrpGroup.Get("hsrpGroup.attributes.name").String())
			} else {
				ncItem.Name = types.StringNull()
			}
			if !ncItem.PreemptDelayMinimum.IsNull() {
				ncItem.PreemptDelayMinimum = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.preemptDelayMin").Int())
			} else {
				ncItem.PreemptDelayMinimum = types.Int64Null()
			}
			if !ncItem.PreemptDelayReload.IsNull() {
				ncItem.PreemptDelayReload = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.preemptDelayReload").Int())
			} else {
				ncItem.PreemptDelayReload = types.Int64Null()
			}
			if !ncItem.PreemptDelaySync.IsNull() {
				ncItem.PreemptDelaySync = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.preemptDelaySync").Int())
			} else {
				ncItem.PreemptDelaySync = types.Int64Null()
			}
			if !ncItem.Priority.IsNull() {
				ncItem.Priority = types.Int64Value(rhsrpGroup.Get("hsrpGroup.attributes.prio").Int())
			} else {
				ncItem.Priority = types.Int64Null()
			}
			item.Groups[nc] = ncItem
		}
		data.Interfaces[key] = item
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin toDeleteBody

func (data HSRP) toDeleteBody() nxos.Body {
	body := ""
	body, _ = sjson.Set(body, data.getClassName()+".attributes.status", "deleted")

	return nxos.Body{Str: body}
}

func (data HSRP) toBodyWithDeletes(ctx context.Context, state HSRP, config HSRP) nxos.Body {
	body := data.toBody(config)
	bodyPath := data.getClassName() + ".children"
	_ = bodyPath
	for stateKey := range state.Interfaces {
		if _, found := data.Interfaces[stateKey]; !found {
			stateChild := state.Interfaces[stateKey]
			deleteBody := ""
			deleteBody, _ = sjson.Set(deleteBody, "hsrpIf.attributes.rn", stateChild.getRn(stateKey))
			deleteBody, _ = sjson.Set(deleteBody, "hsrpIf.attributes.status", "deleted")
			body.Str, _ = sjson.SetRaw(body.Str, bodyPath+".0.hsrpInst.children"+".-1", deleteBody)
		}
	}
	for di := range state.Interfaces {
		if _, found := data.Interfaces[di]; !found {
			continue
		}
		stateItemdi := state.Interfaces[di]
		planItemdi := data.Interfaces[di]
		matchBodyPathdi := ""
		for mi, mv := range gjson.Get(body.Str, bodyPath+".0.hsrpInst.children").Array() {
			if mv.Get("hsrpIf.attributes.rn").String() == stateItemdi.getRn(di) {
				matchBodyPathdi = bodyPath + ".0.hsrpInst.children" + "." + strconv.Itoa(mi) + ".hsrpIf.children"
				break
			}
		}
		if matchBodyPathdi == "" {
			continue
		}
		for stateChildKey := range stateItemdi.Groups {
			if _, found := planItemdi.Groups[stateChildKey]; !found {
				stateChild := stateItemdi.Groups[stateChildKey]
				deleteBody := ""
				deleteBody, _ = sjson.Set(deleteBody, "hsrpGroup.attributes.rn", stateChild.getRn(stateChildKey))
				deleteBody, _ = sjson.Set(deleteBody, "hsrpGroup.attributes.status", "deleted")
				body.Str, _ = sjson.SetRaw(body.Str, matchBodyPathdi+".-1", deleteBody)
			}
		}
	}
	return body
}

// End of section. //template:end toDeleteBody
