// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccNxosLoopbackInterfaceVRF(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccNxosLoopbackInterfaceVRFPrerequisitesConfig + testAccNxosLoopbackInterfaceVRFConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nxos_loopback_interface_vrf.test", "interface_id", "lo123"),
					resource.TestCheckResourceAttr("nxos_loopback_interface_vrf.test", "vrf_dn", "sys/inst-default"),
				),
			},
			{
				ResourceName:  "nxos_loopback_interface_vrf.test",
				ImportState:   true,
				ImportStateId: "sys/intf/lb-[lo123]/rtvrfMbr",
			},
		},
	})
}

const testAccNxosLoopbackInterfaceVRFPrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/intf/lb-[lo123]"
  class_name = "l3LbRtdIf"
  content = {
      id = "lo123"
  }
}

`

func testAccNxosLoopbackInterfaceVRFConfig_minimum() string {
	return `
	resource "nxos_loopback_interface_vrf" "test" {
		interface_id = "lo123"
		vrf_dn = "sys/inst-default"
  		depends_on = [nxos_rest.PreReq0, ]
	}
	`
}

func testAccNxosLoopbackInterfaceVRFConfig_all() string {
	return `
	resource "nxos_loopback_interface_vrf" "test" {
		interface_id = "lo123"
		vrf_dn = "sys/inst-default"
  		depends_on = [nxos_rest.PreReq0, ]
	}
	`
}
