// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"fmt"
	"testing"

	goversion "github.com/hashicorp/go-version"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"
)

func TestAccNxosDHCPRelayAddress(t *testing.T) {
	var tfVersion *goversion.Version
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			terraformVersionCapture{Version: &tfVersion},
		},
		Steps: []resource.TestStep{
			{
				Config: testAccNxosDHCPRelayAddressPrerequisitesConfig + testAccNxosDHCPRelayAddressConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nxos_dhcp_relay_address.test", "interface_id", "eth1/10"),
					resource.TestCheckResourceAttr("nxos_dhcp_relay_address.test", "vrf", "VRF1"),
					resource.TestCheckResourceAttr("nxos_dhcp_relay_address.test", "address", "1.1.1.1"),
				),
			},
			{
				ResourceName:      "nxos_dhcp_relay_address.test",
				ImportState:       true,
				ImportStateIdFunc: nxosDHCPRelayAddressImportStateIdFunc("nxos_dhcp_relay_address.test"),
			},
			{
				ResourceName:    "nxos_dhcp_relay_address.test",
				ImportState:     true,
				ImportStateKind: resource.ImportBlockWithResourceIdentity,
				SkipFunc:        skipBelowTerraformVersion(&tfVersion, goversion.Must(goversion.NewVersion("1.12.0"))),
			},
		},
	})
}

func nxosDHCPRelayAddressImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {
		primary := s.RootModule().Resources[resourceName].Primary
		InterfaceId := primary.Attributes["interface_id"]
		Vrf := primary.Attributes["vrf"]
		Address := primary.Attributes["address"]

		return fmt.Sprintf("%s,%s,%s", InterfaceId, Vrf, Address), nil
	}
}

const testAccNxosDHCPRelayAddressPrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/fm/dhcp"
  class_name = "fmDhcp"
  delete = false
  content = {
      adminSt = "enabled"
  }
}

resource "nxos_rest" "PreReq1" {
  dn = "sys/intf/phys-[eth1/10]"
  class_name = "l1PhysIf"
  content = {
      layer = "Layer3"
  }
}

resource "nxos_rest" "PreReq2" {
  dn = "sys/dhcp/inst/relayif-[eth1/10]"
  class_name = "dhcpRelayIf"
  content = {
      id = "eth1/10"
  }
  depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, ]
}

`

func testAccNxosDHCPRelayAddressConfig_minimum() string {
	return `
	resource "nxos_dhcp_relay_address" "test" {
		interface_id = "eth1/10"
		vrf = "VRF1"
		address = "1.1.1.1"
  		depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, ]
	}
	`
}

func testAccNxosDHCPRelayAddressConfig_all() string {
	return `
	resource "nxos_dhcp_relay_address" "test" {
		interface_id = "eth1/10"
		vrf = "VRF1"
		address = "1.1.1.1"
  		depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, ]
	}
	`
}
