// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"testing"

	goversion "github.com/hashicorp/go-version"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc
func TestAccNxosNetflow(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.description", "Netflow exporter"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.destination_ip", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.destination_port", "9995"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.dscp", "46"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.source_interface", "lo0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.version", "v9"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "exporters.EXPORTER1.vrf_name", "default"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "records.RECORD1.description", "Netflow record"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "records.RECORD1.collect_parameters", "count-bytes"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "records.RECORD1.match_parameters", "src-ipv4"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "monitors.MONITOR1.description", "Netflow monitor"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "monitors.MONITOR1.exporter_buckets.1.description", "Bucket 1"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "monitors.MONITOR1.exporter_buckets.1.hash_high", "4294967295"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "monitors.MONITOR1.exporter_buckets.1.hash_low", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "hardware_profiles.HWPROFILE1.description", "Hardware profile"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "hardware_profiles.HWPROFILE1.burst_interval_shift", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "hardware_profiles.HWPROFILE1.export_interval", "200"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "hardware_profiles.HWPROFILE1.ip_packet_id_shift", "10"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "hardware_profiles.HWPROFILE1.mtu", "1500"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_netflow.test", "hardware_profiles.HWPROFILE1.source_port", "10000"))
	var tfVersion *goversion.Version
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			terraformVersionCapture{Version: &tfVersion},
		},
		Steps: []resource.TestStep{
			{
				Config: testAccNxosNetflowConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:      "nxos_netflow.test",
				ImportState:       true,
				ImportStateIdFunc: nxosNetflowImportStateIdFunc("nxos_netflow.test"),
			},
			{
				ResourceName:       "nxos_netflow.test",
				ImportState:        true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
				ExpectNonEmptyPlan: true,
				SkipFunc:           skipBelowTerraformVersion(&tfVersion, goversion.Must(goversion.NewVersion("1.12.0"))),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc
func nxosNetflowImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {

		return fmt.Sprintf(""), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal
func testAccNxosNetflowConfig_minimum() string {
	config := `resource "nxos_netflow" "test" {` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll
func testAccNxosNetflowConfig_all() string {
	config := `resource "nxos_netflow" "test" {` + "\n"
	config += `	exporters = {` + "\n"
	config += `		"EXPORTER1" = {` + "\n"
	config += `			description = "Netflow exporter"` + "\n"
	config += `			destination_ip = "10.1.1.1"` + "\n"
	config += `			destination_port = 9995` + "\n"
	config += `			dscp = 46` + "\n"
	config += `			source_interface = "lo0"` + "\n"
	config += `			version = "v9"` + "\n"
	config += `			vrf_name = "default"` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	records = {` + "\n"
	config += `		"RECORD1" = {` + "\n"
	config += `			description = "Netflow record"` + "\n"
	config += `			collect_parameters = "count-bytes"` + "\n"
	config += `			match_parameters = "src-ipv4"` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	monitors = {` + "\n"
	config += `		"MONITOR1" = {` + "\n"
	config += `			description = "Netflow monitor"` + "\n"
	config += `			exporter_buckets = {` + "\n"
	config += `				"1" = {` + "\n"
	config += `					description = "Bucket 1"` + "\n"
	config += `					hash_high = 4294967295` + "\n"
	config += `					hash_low = 0` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	hardware_profiles = {` + "\n"
	config += `		"HWPROFILE1" = {` + "\n"
	config += `			description = "Hardware profile"` + "\n"
	config += `			burst_interval_shift = 10` + "\n"
	config += `			export_interval = 200` + "\n"
	config += `			ip_packet_id_shift = 10` + "\n"
	config += `			mtu = 1500` + "\n"
	config += `			source_port = 10000` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	class_maps = {` + "\n"
	config += `		"CMAP1" = {` + "\n"
	config += `			match_acls = {` + "\n"
	config += `				"ACL1" = {` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
