// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccNxosOSPFVRF(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccNxosOSPFConfig_all(),
			},
			{
				Config: testAccNxosOSPFConfig_all() + testAccNxosOSPFInstanceConfig_all(),
			},
			{
				Config: testAccNxosOSPFConfig_all() + testAccNxosOSPFInstanceConfig_all() + testAccNxosOSPFVRFConfig_minimum(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "instance_name", "OSPF1"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "name", "default"),
				),
			},
			{
				Config: testAccNxosOSPFConfig_all() + testAccNxosOSPFInstanceConfig_all() + testAccNxosOSPFVRFConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "instance_name", "OSPF1"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "name", "default"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "admin_state", "enabled"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "bandwidth_reference", "400000"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "banwidth_reference_unit", "mbps"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "distance", "110"),
					resource.TestCheckResourceAttr("nxos_ospf_vrf.test", "router_id", "34.56.78.90"),
				),
			},
			{
				ResourceName:  "nxos_ospf_vrf.test",
				ImportState:   true,
				ImportStateId: "sys/ospf/inst-[OSPF1]/dom-[default]",
			},
		},
	})
}

func testAccNxosOSPFVRFConfig_minimum() string {
	return `
	resource "nxos_ospf_vrf" "test" {
		instance_name = "OSPF1"
		name = "default"
	}
	`
}

func testAccNxosOSPFVRFConfig_all() string {
	return `
	resource "nxos_ospf_vrf" "test" {
		instance_name = "OSPF1"
		name = "default"
		admin_state = "enabled"
		bandwidth_reference = 400000
		banwidth_reference_unit = "mbps"
		distance = 110
		router_id = "34.56.78.90"
	}
	`
}
