// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-nxos/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/identityschema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var _ resource.Resource = &KeychainResource{}
var _ resource.ResourceWithIdentity = &KeychainResource{}
var _ resource.ResourceWithModifyPlan = &KeychainResource{}

func NewKeychainResource() resource.Resource {
	return &KeychainResource{}
}

type KeychainResource struct {
	data *NxosProviderData
}

func (r *KeychainResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_keychain"
}

func (r *KeychainResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: helpers.NewResourceDescription("This resource can manage the keychain configuration on NX-OS devices, including keychains and their associated key entries.").AddApiDocumentation("kcmgrEntity", "Security%20and%20Policing/kcmgr:Entity/", []string{"kcmgrKeychains", "kcmgrClassicKeychain", "kcmgrKey", "kcmgrMacsecKeychain", "kcmgrMacsecKeyId", "kcmgrMacsecSendlifetime", "kcmgrMacsecpsk"}, []string{"Security%20and%20Policing/kcmgr:Keychains/", "Security%20and%20Policing/kcmgr:ClassicKeychain/", "Security%20and%20Policing/kcmgr:Key/", "Security%20and%20Policing/kcmgr:MacsecKeychain/", "Security%20and%20Policing/kcmgr:MacsecKeyId/", "Security%20and%20Policing/kcmgr:MacsecSendlifetime/", "Security%20and%20Policing/kcmgr:Macsecpsk/"}).String,

		Attributes: map[string]schema.Attribute{
			"device": schema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The distinguished name of the object.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"admin_state": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The administrative state of the object or policy.").AddStringEnumDescription("enabled", "disabled").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("enabled", "disabled"),
				},
			},
			"keychains": schema.MapNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("List of keychains.\n  - Map key: `name` - Keychain name.").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"keys": schema.MapNestedAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("List of keys.\n  - Map key: `key_id` - keyId of classic key chain.\n  - Key range: `0`-`65535`").String,
							Optional:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"cryptographic_algorithm": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("Cryptographic Algorithm used in key.").AddStringEnumDescription("NONE", "MD5", "HMAC-SHA-1", "HMAC-SHA-256", "HMAC-SHA-384", "HMAC-SHA-512", "3DES", "AES").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("NONE", "MD5", "HMAC-SHA-1", "HMAC-SHA-256", "HMAC-SHA-384", "HMAC-SHA-512", "3DES", "AES"),
										},
									},
									"encryption_type": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("Encryption type value based on user input.").AddStringEnumDescription("unencrypted", "type7", "type6").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("unencrypted", "type7", "type6"),
										},
									},
									"key_string": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("keyString provided by user for the keychain.").String,
										Optional:            true,
										Sensitive:           true,
									},
									"key_string_wo": schema.StringAttribute{
										MarkdownDescription: "The write-only value of the attribute.",
										WriteOnly:           true,
										Optional:            true,
									},
									"key_string_wo_version": schema.Int64Attribute{
										MarkdownDescription: "The write-only version of the attribute.",
										Optional:            true,
									},
								},
							},
						},
					},
				},
			},
			"macsec_keychains": schema.MapNestedAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("List of MACsec keychains.\n  - Map key: `name` - Keychain name of macseckeychain.").String,
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"keys": schema.MapNestedAttribute{
							MarkdownDescription: helpers.NewAttributeDescription("List of MACsec keys.\n  - Map key: `key_id` - keyId of macseckeychain.").String,
							Optional:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"cryptographic_algorithm": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("cryptographicAlgo of macseckeychain.").AddStringEnumDescription("AES_128_CMAC", "AES_256_CMAC").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("AES_128_CMAC", "AES_256_CMAC"),
										},
									},
									"encryption_type": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("Encryption type of macseckeychain.").AddStringEnumDescription("unencrypted", "type7", "type6").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("unencrypted", "type7", "type6"),
										},
									},
									"key_hex_string": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("keystring of macseckeychain.").String,
										Optional:            true,
										Sensitive:           true,
									},
									"key_hex_string_wo": schema.StringAttribute{
										MarkdownDescription: "The write-only value of the attribute.",
										WriteOnly:           true,
										Optional:            true,
									},
									"key_hex_string_wo_version": schema.Int64Attribute{
										MarkdownDescription: "The write-only version of the attribute.",
										Optional:            true,
									},
									"duration": schema.Int64Attribute{
										MarkdownDescription: helpers.NewAttributeDescription("duration period of lifetime.").AddIntegerRangeDescription(0, 2147483646).String,
										Optional:            true,
										Validators: []validator.Int64{
											int64validator.Between(0, 2147483646),
										},
									},
									"end_day": schema.Int64Attribute{
										MarkdownDescription: helpers.NewAttributeDescription("Ending date of lifetime for the keychain.").AddIntegerRangeDescription(0, 31).String,
										Optional:            true,
										Validators: []validator.Int64{
											int64validator.Between(0, 31),
										},
									},
									"end_month": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("Ending month of lifetime for the keychain.").AddStringEnumDescription("Unspecified", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("Unspecified", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
										},
									},
									"end_time": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("HH:MM:SS End Time of lifetime.").String,
										Optional:            true,
									},
									"end_year": schema.Int64Attribute{
										MarkdownDescription: helpers.NewAttributeDescription("Ending Year of lifetime for the keychain.").AddIntegerRangeDescription(0, 2035).String,
										Optional:            true,
										Validators: []validator.Int64{
											int64validator.Between(0, 2035),
										},
									},
									"infinite": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("Lifetime has no endtime.").AddStringEnumDescription("disabled", "enabled").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("disabled", "enabled"),
										},
									},
									"local": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("local timezone notification.").AddStringEnumDescription("unspecified", "local").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("unspecified", "local"),
										},
									},
									"start_day": schema.Int64Attribute{
										MarkdownDescription: helpers.NewAttributeDescription("starting Day of Lifetime for the keychain.").AddIntegerRangeDescription(0, 31).String,
										Optional:            true,
										Validators: []validator.Int64{
											int64validator.Between(0, 31),
										},
									},
									"start_month": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("starting month of Lifetime for the keychain.").AddStringEnumDescription("Unspecified", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec").String,
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.OneOf("Unspecified", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
										},
									},
									"start_time": schema.StringAttribute{
										MarkdownDescription: helpers.NewAttributeDescription("HH:MM:SS Start Time of lifetime.").String,
										Optional:            true,
									},
									"start_year": schema.Int64Attribute{
										MarkdownDescription: helpers.NewAttributeDescription("starting Year of Lifetime for the keychain.").AddIntegerRangeDescription(0, 2035).String,
										Optional:            true,
										Validators: []validator.Int64{
											int64validator.Between(0, 2035),
										},
									},
								},
							},
						},
					},
				},
			},
			"macsec_psk_no_show": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("macsec-psk hide them in show.").AddStringEnumDescription("disabled", "enabled").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("disabled", "enabled"),
				},
			},
		},
	}
}

func (r *KeychainResource) IdentitySchema(ctx context.Context, req resource.IdentitySchemaRequest, resp *resource.IdentitySchemaResponse) {
	resp.IdentitySchema = identityschema.Schema{
		Attributes: map[string]identityschema.Attribute{
			"device": identityschema.StringAttribute{
				Description:       "A device name from the provider configuration.",
				OptionalForImport: true,
			},
		},
	}
}

func (r *KeychainResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	r.data = req.ProviderData.(*NxosProviderData)
}

// ModifyPlan rejects configurations using objects not supported by the NX-OS version of the device,
// so that the error surfaces during plan rather than apply. It also forces a recompute during the
// leniency window that follows an import, so that Update always runs (and clears the `importing`
// flag) even when the plan would otherwise be a no-op. Without this, a first post-import config that
// happens to declare every entry with matching values would never invoke Update, leaving `importing`
// stuck and later, genuine removals silently un-reconciled.
func (r *KeychainResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		return
	}

	// The check is skipped if the plan cannot be fully evaluated yet (e.g. unknown map keys or device);
	// Create and Update repeat it before sending the request.
	if len(KeychainMinVersions) > 0 && r.data != nil {
		var plan, config Keychain
		if !req.Plan.Get(ctx, &plan).HasError() && !req.Config.Get(ctx, &config).HasError() && !plan.Device.IsUnknown() {
			if device, ok := r.data.Devices[plan.Device.ValueString()]; ok && device.Managed {
				resp.Diagnostics.Append(helpers.CheckMinVersion(ctx, device.Client, plan.Device.ValueString(), plan.toBody(config).Str, KeychainMinVersions)...)
				if resp.Diagnostics.HasError() {
					return
				}
			}
		}
	}

	if req.State.Raw.IsNull() {
		return
	}

	imp, diags := helpers.IsFlagImporting(ctx, req.Private)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() || !imp {
		return
	}

	resp.Diagnostics.Append(resp.Plan.SetAttribute(ctx, path.Root("id"), types.StringUnknown())...)
}

// End of section. //template:end model

// Section below is generated&owned by "gen/generator.go". //template:begin create
func (r *KeychainResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan Keychain

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	var config Keychain
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getDn()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to find device '%s' in provider configuration", plan.Device.ValueString()))
		return
	}

	// Post object
	if device.Managed {
		body := plan.toBody(config)
		resp.Diagnostics.Append(helpers.CheckMinVersion(ctx, device.Client, plan.Device.ValueString(), body.Str, KeychainMinVersions)...)
		if resp.Diagnostics.HasError() {
			return
		}
		_, err := device.Client.Post(plan.getDn(), body.Str)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to post object, got error: %s", err))
			return
		}
	}

	plan.Dn = types.StringValue(plan.getDn())
	var identity KeychainIdentity
	identity.toIdentity(ctx, &plan)

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getDn()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	diags = resp.Identity.Set(ctx, &identity)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end create

// Section below is generated&owned by "gen/generator.go". //template:begin read
func (r *KeychainResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state Keychain

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read identity if available (requires Terraform >= 1.12.0)
	if req.Identity != nil && !req.Identity.Raw.IsNull() {
		var identity KeychainIdentity
		diags = req.Identity.Get(ctx, &identity)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}
		state.fromIdentity(ctx, &identity)
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Dn.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to find device '%s' in provider configuration", state.Device.ValueString()))
		return
	}

	if device.Managed {
		res, err := device.GetSubtree(ctx, state.Dn.ValueString(), []string{"kcmgrKeychains", "kcmgrClassicKeychain", "kcmgrKey", "kcmgrMacsecKeychain", "kcmgrMacsecKeyId", "kcmgrMacsecSendlifetime", "kcmgrMacsecpsk"}, KeychainSubtreeClassMinVersions)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
			return
		}

		if !res.Exists() {
			resp.State.RemoveResource(ctx)
			return
		}

		imp, diags := helpers.IsFlagImporting(ctx, req.Private)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}
		if imp {
			state.fromBody(res)
			// Warn here rather than in ModifyPlan: Terraform reuses this same refresh for both the
			// preview plan and the plan it recomputes right before applying, so Read only runs once
			// per operation - unlike ModifyPlan, which runs (and would warn) twice.
			resp.Diagnostics.AddWarning(
				"Import leniency in effect",
				"This resource was recently imported. If the plan shows entries or attributes disappearing, "+
					"that's expected: Terraform will stop tracking anything not declared in your configuration, "+
					"but nothing will change on the device. This notice won't appear again after your next apply.",
			)
		} else {
			state.updateFromBody(res)
		}
	}

	var identity KeychainIdentity
	identity.toIdentity(ctx, &state)

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Dn.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	diags = resp.Identity.Set(ctx, &identity)
	resp.Diagnostics.Append(diags...)
}

// End of section. //template:end read

// Section below is generated&owned by "gen/generator.go". //template:begin update
func (r *KeychainResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan Keychain

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read config
	var config Keychain
	diags = req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state Keychain

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.getDn()))

	device, ok := r.data.Devices[plan.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to find device '%s' in provider configuration", plan.Device.ValueString()))
		return
	}

	imp, diags := helpers.IsFlagImporting(ctx, req.Private)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if device.Managed {
		body := plan.toBodyWithDeletes(ctx, state, config, imp)
		resp.Diagnostics.Append(helpers.CheckMinVersion(ctx, device.Client, plan.Device.ValueString(), body.Str, KeychainMinVersions)...)
		if resp.Diagnostics.HasError() {
			return
		}
		_, err := device.Client.Post(plan.getDn(), body.Str)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to update object, got error: %s", err))
			return
		}
	}

	plan.Dn = types.StringValue(plan.getDn())
	var identity KeychainIdentity
	identity.toIdentity(ctx, &plan)

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.getDn()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	diags = resp.Identity.Set(ctx, &identity)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end update

// Section below is generated&owned by "gen/generator.go". //template:begin delete
func (r *KeychainResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state Keychain

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Dn.ValueString()))

	device, ok := r.data.Devices[state.Device.ValueString()]
	if !ok {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to find device '%s' in provider configuration", state.Device.ValueString()))
		return
	}

	if device.Managed {
		body := state.toDeleteBody()
		if len(body.Str) > 0 {
			_, err := device.Client.Post(state.getDn(), body.Str)
			if err != nil {
				resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Dn.ValueString()))

	resp.State.RemoveResource(ctx)
}

// End of section. //template:end delete

// Section below is generated&owned by "gen/generator.go". //template:begin import
func (r *KeychainResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if req.ID != "" || req.Identity == nil || req.Identity.Raw.IsNull() {
		idParts := strings.Split(req.ID, ",")
		idParts = helpers.RemoveEmptyStrings(idParts)

		if len(idParts) != 0 && len(idParts) != 1 {
			expectedIdentifier := "Expected import identifier with format: ''"
			expectedIdentifier += " or '<device>'"
			resp.Diagnostics.AddError(
				"Unexpected Import Identifier",
				fmt.Sprintf("%s. Got: %q", expectedIdentifier, req.ID),
			)
			return
		}
		if len(idParts) == 1 {
			resp.Diagnostics.Append(resp.Identity.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), idParts[len(idParts)-1])...)
		}
	} else {
		var identity KeychainIdentity
		diags := req.Identity.Get(ctx, &identity)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}
		if !identity.Device.IsNull() && !identity.Device.IsUnknown() {
			resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("device"), identity.Device.ValueString())...)
		}
	}

	var state Keychain
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), state.getDn())...)

	helpers.SetFlagImporting(ctx, true, resp.Private, &resp.Diagnostics)
}

// End of section. //template:end import
