// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"fmt"
	"testing"

	goversion "github.com/hashicorp/go-version"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"
)

func TestAccNxosDefaultQOSPolicyMapMatchClassMapPolice(t *testing.T) {
	var tfVersion *goversion.Version
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			terraformVersionCapture{Version: &tfVersion},
		},
		Steps: []resource.TestStep{
			{
				Config: testAccNxosDefaultQOSPolicyMapMatchClassMapPolicePrerequisitesConfig + testAccNxosDefaultQOSPolicyMapMatchClassMapPoliceConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "policy_map_name", "PM1"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "class_map_name", "Voice"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "bc_rate", "200"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "bc_unit", "mbytes"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "be_rate", "200"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "be_unit", "mbytes"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "cir_rate", "10000"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "cir_unit", "mbps"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "conform_action", "transmit"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "conform_set_cos", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "conform_set_dscp", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "conform_set_precedence", "routine"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "conform_set_qos_group", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "exceed_action", "transmit"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "exceed_set_cos", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "exceed_set_dscp", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "exceed_set_precedence", "routine"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "exceed_set_qos_group", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "pir_rate", "10000"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "pir_unit", "mbps"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "violate_action", "drop"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "violate_set_cos", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "violate_set_dscp", "0"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "violate_set_precedence", "routine"),
					resource.TestCheckResourceAttr("nxos_default_qos_policy_map_match_class_map_police.test", "violate_set_qos_group", "0"),
				),
			},
			{
				ResourceName:      "nxos_default_qos_policy_map_match_class_map_police.test",
				ImportState:       true,
				ImportStateIdFunc: nxosDefaultQOSPolicyMapMatchClassMapPoliceImportStateIdFunc("nxos_default_qos_policy_map_match_class_map_police.test"),
			},
			{
				ResourceName:    "nxos_default_qos_policy_map_match_class_map_police.test",
				ImportState:     true,
				ImportStateKind: resource.ImportBlockWithResourceIdentity,
				SkipFunc:        skipBelowTerraformVersion(&tfVersion, goversion.Must(goversion.NewVersion("1.12.0"))),
			},
		},
	})
}

func nxosDefaultQOSPolicyMapMatchClassMapPoliceImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {
		primary := s.RootModule().Resources[resourceName].Primary
		PolicyMapName := primary.Attributes["policy_map_name"]
		ClassMapName := primary.Attributes["class_map_name"]

		return fmt.Sprintf("%s,%s", PolicyMapName, ClassMapName), nil
	}
}

const testAccNxosDefaultQOSPolicyMapMatchClassMapPolicePrerequisitesConfig = `
resource "nxos_rest" "PreReq0" {
  dn = "sys/ipqos/dflt/p/name-[PM1]"
  class_name = "ipqosPMapInst"
  content = {
      name = "PM1"
  }
}

resource "nxos_rest" "PreReq1" {
  dn = "sys/ipqos/dflt/c/name-[Voice]"
  class_name = "ipqosCMapInst"
  content = {
      name = "Voice"
  }
}

resource "nxos_rest" "PreReq2" {
  dn = "sys/ipqos/dflt/p/name-[PM1]/cmap-[Voice]"
  class_name = "ipqosMatchCMap"
  content = {
      name = "Voice"
  }
  depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, ]
}

`

func testAccNxosDefaultQOSPolicyMapMatchClassMapPoliceConfig_minimum() string {
	return `
	resource "nxos_default_qos_policy_map_match_class_map_police" "test" {
		policy_map_name = "PM1"
		class_map_name = "Voice"
		cir_rate = 10000
  		depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, ]
	}
	`
}

func testAccNxosDefaultQOSPolicyMapMatchClassMapPoliceConfig_all() string {
	return `
	resource "nxos_default_qos_policy_map_match_class_map_police" "test" {
		policy_map_name = "PM1"
		class_map_name = "Voice"
		bc_rate = 200
		bc_unit = "mbytes"
		be_rate = 200
		be_unit = "mbytes"
		cir_rate = 10000
		cir_unit = "mbps"
		conform_action = "transmit"
		conform_set_cos = 0
		conform_set_dscp = 0
		conform_set_precedence = "routine"
		conform_set_qos_group = 0
		exceed_action = "transmit"
		exceed_set_cos = 0
		exceed_set_dscp = 0
		exceed_set_precedence = "routine"
		exceed_set_qos_group = 0
		pir_rate = 10000
		pir_unit = "mbps"
		violate_action = "drop"
		violate_set_cos = 0
		violate_set_dscp = 0
		violate_set_precedence = "routine"
		violate_set_qos_group = 0
  		depends_on = [nxos_rest.PreReq0, nxos_rest.PreReq1, nxos_rest.PreReq2, ]
	}
	`
}
