// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"testing"

	goversion "github.com/hashicorp/go-version"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc
func TestAccNxosDefaultQoS(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "class_maps.Voice.match_type", "match-any"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_type", "match-any"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.set_qos_group_id", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_bc_rate", "200"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_bc_unit", "mbytes"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_be_rate", "200"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_be_unit", "mbytes"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_cir_rate", "10000"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_cir_unit", "mbps"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_conform_action", "transmit"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_conform_set_cos", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_conform_set_dscp", "af22"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_conform_set_precedence", "routine"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_conform_set_qos_group", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_exceed_action", "transmit"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_exceed_set_cos", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_exceed_set_dscp", "af31"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_exceed_set_precedence", "routine"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_exceed_set_qos_group", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_pir_rate", "10000"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_pir_unit", "mbps"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_violate_action", "drop"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_violate_set_cos", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_violate_set_dscp", "cs1"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_violate_set_precedence", "routine"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_maps.PM1.match_class_maps.Voice.police_violate_set_qos_group", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_interface_in.eth1/10.policy_map_name", "PM1"))
	checks = append(checks, resource.TestCheckResourceAttr("nxos_default_qos.test", "policy_interface_in.eth1/10.policy_map_statistics", "false"))
	var tfVersion *goversion.Version
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			terraformVersionCapture{Version: &tfVersion},
		},
		Steps: []resource.TestStep{
			{
				Config: testAccNxosDefaultQoSConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:      "nxos_default_qos.test",
				ImportState:       true,
				ImportStateIdFunc: nxosDefaultQoSImportStateIdFunc("nxos_default_qos.test"),
			},
			{
				ResourceName:       "nxos_default_qos.test",
				ImportState:        true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
				ExpectNonEmptyPlan: true,
				SkipFunc:           skipBelowTerraformVersion(&tfVersion, goversion.Must(goversion.NewVersion("1.12.0"))),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc
func nxosDefaultQoSImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {

		return fmt.Sprintf(""), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal
func testAccNxosDefaultQoSConfig_minimum() string {
	config := `resource "nxos_default_qos" "test" {` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll
func testAccNxosDefaultQoSConfig_all() string {
	config := `resource "nxos_default_qos" "test" {` + "\n"
	config += `	class_maps = {` + "\n"
	config += `		"Voice" = {` + "\n"
	config += `			match_type = "match-any"` + "\n"
	config += `			dscp_values = {` + "\n"
	config += `				"ef" = {` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	policy_maps = {` + "\n"
	config += `		"PM1" = {` + "\n"
	config += `			match_type = "match-any"` + "\n"
	config += `			match_class_maps = {` + "\n"
	config += `				"Voice" = {` + "\n"
	config += `					set_qos_group_id = 1` + "\n"
	config += `					police_bc_rate = 200` + "\n"
	config += `					police_bc_unit = "mbytes"` + "\n"
	config += `					police_be_rate = 200` + "\n"
	config += `					police_be_unit = "mbytes"` + "\n"
	config += `					police_cir_rate = 10000` + "\n"
	config += `					police_cir_unit = "mbps"` + "\n"
	config += `					police_conform_action = "transmit"` + "\n"
	config += `					police_conform_set_cos = 0` + "\n"
	config += `					police_conform_set_dscp = "af22"` + "\n"
	config += `					police_conform_set_precedence = "routine"` + "\n"
	config += `					police_conform_set_qos_group = 0` + "\n"
	config += `					police_exceed_action = "transmit"` + "\n"
	config += `					police_exceed_set_cos = 0` + "\n"
	config += `					police_exceed_set_dscp = "af31"` + "\n"
	config += `					police_exceed_set_precedence = "routine"` + "\n"
	config += `					police_exceed_set_qos_group = 0` + "\n"
	config += `					police_pir_rate = 10000` + "\n"
	config += `					police_pir_unit = "mbps"` + "\n"
	config += `					police_violate_action = "drop"` + "\n"
	config += `					police_violate_set_cos = 0` + "\n"
	config += `					police_violate_set_dscp = "cs1"` + "\n"
	config += `					police_violate_set_precedence = "routine"` + "\n"
	config += `					police_violate_set_qos_group = 0` + "\n"
	config += `				}` + "\n"
	config += `			}` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `	policy_interface_in = {` + "\n"
	config += `		"eth1/10" = {` + "\n"
	config += `			policy_map_name = "PM1"` + "\n"
	config += `			policy_map_statistics = false` + "\n"
	config += `		}` + "\n"
	config += `	}` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
